- conf/machine/dragonboard-410c.conf
This makes wifi work out of the box:
root@dragonboard-410c:~# dmesg | grep wcn | grep -v Cap
[    0.224776] irq: no irq domain found for /soc/wcnss-smp2p/slave-kernel !
[    2.074374]  remoteproc0: Direct firmware load for wcnss.mdt failed with error -2
[    4.953539] wcnss: IRIS Reg: 0x51120004
[    5.165072]  remoteproc0: Booting fw image wcnss.mdt, size 7260
[    8.576187] wcnss: received WCNSS_CBC_COMPLETE_IND from FW
[    8.577049] wcn36xx-msm a000000.qcom,wcn36xx: wcn36xx_msm_probe initialized
[    8.596453] wcn36xx wcn36xx: Direct firmware load for wlan/macaddr0 failed with error -2
[    8.596545] wcn36xx wcn36xx: Failed (-2) to read macaddressfile wlan/macaddr0, using a random address instead
[    8.606677] wcn36xx: mac address: 00:0a:f5:3e:dd:52
[    9.019923] wcn36xx: firmware …
> dragonboard-410c: recommend wifi modules

- recipes-devtools/skales/skales_git.bb
This fixes a build error I ran into testing jethro on the dragonboard.
dtbTool (provided by skales) uses dtc. The skales recipe depends on dtc, but not the native version. If dtc-native is not built/installed to the sysroot before virtual/kernel deploy is run, the build fails. Since skales is a native recipe, it seems correct to use -native deps.
I reproduced the error by simply running the deploy recipe from a clean state. 'bitbake -c deploy virtual/kernel'
> skales-native: depend on -native recipes for python & dtc

- recipes-multimedia/alsa/files/0001-ucm-Add-ucm-files-for-DB410c-board.patch
Upstream has added support for another hardware platform so this patch needs a
small adjustment to continue to apply.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
> alsa-lib: fix patch

- recipes-bsp/firmware/firmware-qcom-dragonboard410c_1.3.0.bb
The self-extraction shell script for the firmware uses the 'bc' command.  I ran into a failure on a build server that happened to not have that utility installed already.  Adding the dependency takes are of it.
> firmware-qcom-dragonboard410c: add missing dependency

- recipes-kernel/linux/linux-linaro-qcom.inc
- recipes-kernel/linux/linux-linaro-qcomlt-tracking_4.6.bb
- recipes-kernel/linux/linux-linaro-qcomlt_4.4.bb
- recipes-kernel/linux/linux-qcom-bootimg.inc
Moves settings and a function _append that were duplicated across the kernel recipes into common .inc files.
> Kernel recipe patches v2, part 1 - reduce duplication

- conf/eula/dragonboard-410c-32
- conf/machine/dragonboard-410c-32.conf
- conf/machine/include/qcom-apq8016.inc
- recipes-bsp/firmware/firmware-qcom-dragonboard410c_1.3.0.bb
This adds a 32-bit db410c machine.
On of the usage scenarios is to build a 32-bit rootfs using this machine, and to combine it with the kernel and the modules from a 64-bit build. The 32-bit linux kernel is not needed, so we use "linux-dummy" for virtual/kernel provider, and don't include the kernel into the rootfs image.
> dragonboard-410c: create 32-bit machine configuration

- recipes-kernel/linux/linux-linaro-qcomlt_4.4.bb
This kernel uses dtbTool ( a python script) during build
this script ends up poking at host python and if you use
something like archlinux then your python version will be
different then python-native and it will result in compile
errors e.g.
| Traceback (most recent call last):
|   File "/mnt/b/build/tmp-glibc/sysroots/x86_64-linux/usr/bin/dtbTool", line 34, in <module>
|     from struct import pack, unpack
|   File "/usr/lib/python2.7/struct.py", line 1, in <module>
|     from _struct import *
| ImportError: /usr/lib/python2.7/lib-dynload/_struct.so: undefined symbol: PyUnicodeUCS4_AsEncodedString
therefore inherit pythonnative to limit it to use the python
from native sysroot for consistency across different build hosts
> linux-linaro-qcomlt_4.4.bb: Inherit pythonnative

- recipes-support/qrtr/qrtr_git.bb
* upstream has fixed multilib/multiarch, so update recipe accordingly
* also fixes "QA Issue: No GNU_HASH in the elf binary"
> qrtr: upgrade recipe version

- recipes-kernel/linux/linux-linaro-qcomlt-db820c_4.11.bb
- recipes-kernel/linux/linux-linaro-qcomlt_4.9.bb
Device tree support is now handled by the kernel class.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
> linux-linaro-qcomlt: stop using linux-dtb.inc

- conf/machine/dragonboard-410c.conf
Prefer the compressed version of the sdcard image by default as it is
substantially smaller.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
> dragonboard-410c.conf: use wic.gz by default

- conf/machine/dragonboard-410c.conf
It would allow us to avoid uncompressing wic image every time
we update SD card with new image using bmap-tools.
Signed-off-by: Héctor Orón Martínez <hector.oron@collabora.co.uk>
> dragonboard-410c.conf: add wic.bmap image type

- recipes-bsp/firmware/firmware-qcom-dragonboard410c_1032.1.bb
- recipes-bsp/firmware/firmware-qcom-dragonboard820c_01700.1.bb
Hardcoded /lib is not compatible with usrmerge.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
> firmware-qcom: use nonarch_base_libdir instead of /lib

- conf/machine/dragonboard-820c.conf
The last bootloader dosen't include the system partition so use
rootfs instead [1], the same change was applied in Debian build [2].
[1]
http://snapshots.linaro.org/96boards/dragonboard820c/linaro/rescue/27/
[2]
https://git.linaro.org/ci/job/configs.git/commit/?id=b4684a2f44
> conf/machine: dragonboard-820c.conf change to use rootfs (sda7)

- conf/machine/dragonboard-410c.conf
- conf/machine/dragonboard-820c.conf
Both boards are supported by u-boot upstream (chainloaded from lk).
> Define default u-boot machine for db410c and db820c

- recipes-test/bootrr/bootrr.bb
- recipes-test/images/initramfs-bootrr-image.bb
- recipes-test/initrdscripts/bootrr-init.bb
- recipes-test/initrdscripts/files/init-debug.sh
- recipes-test/lava-test-shell/lava-test-shell.bb
A minimal ramdisk suitable for testing, imported from,
https://github.com/andersson/meta-stuff
Recipes added,
- bootrr: Boot regression testing
- lava-test-shell: Lava test shell helpers to execute bootrr
outside LAVA environment
LAVA test definition run example,
https://validation.linaro.org/scheduler/job/1692990
> recipes-test: Add initramfs-bootrr-image

- conf/machine/dragonboard-410c.conf
- conf/machine/include/qcom-apq8016.inc
- conf/machine/include/qcom-apq8064.inc
- conf/machine/include/qcom-apq8096.inc
As discussed on https://github.com/ndechesne/meta-qcom/issues/61, using _append
will modify IMAGE_FSTYPES unconditionnally and won't give DISTRO a chance to
override.
Let's set sane, default settings using ?= (or +=). If a DISTRO wants to change
them, we suppose they know what they do, and overwrite correctly.
Reported-by: Jan-Simon Möller <jsmoeller@linuxfoundation.org>
> machine: do not use _append for IMAGE_FSTYPES

- conf/layer.conf
Allows the user to easily identify if the layer is compatible with
oe-core.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
> layer.conf: add LAYERSERIES_COMPAT markup

- recipes-test/bootrr/bootrr.bb
- recipes-test/initrdscripts/files/init-debug.sh
This bumps the bootrr recipe to use the latest commit from the bootrr project, fixes kernel module auto loading and makes it possible to automatically run the bootrr board scripts in a LAVAless environment.
> Enable lab-bjorn to run straight off qcom/rocko

- recipes-test/bootrr/bootrr.bb
Bjorn Andersson (2):
helpers: Allow timeout in assert_driver as well
boards: db820c: Test for atl1c and ath10k_pci
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
> bootrr: Bump revision

- recipes-test/diag/diag_git.bb
Bjorn Andersson (1):
qrtr: Register the DCI and not DCI_CMD instance
Khem Raj (1):
Fix build with musl
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
> diag: Bump revision to fix SDM845 support

- conf/machine/include/qcom-apq8016.inc
- recipes-support/rmtfs/files/rmtfs.service
To workaround problems when the DSP isn't ready load
qcom_q6v5_pil after rmtfs, blacklist the module to avoid
autoload on boot.
> conf/machine/include/qcom-apq8016.inc: Load qcom_q6v5_pil afer rmtfs 

- recipes-kernel/linux/linux-linaro-qcomlt_4.14.bb
Changeset,
0407ad53548e Merge tag 'v4.14.90' into release/qcomlt-4.14
037d52f70643 Merge remote-tracking branch 'loic/qcomlt-4.14-usb' into release/qcomlt-4.14
6d39111aacb6 Merge remote-tracking branch 'loic/qcomlt-4.14-watchdog' into release/qcomlt-4.14
4bcf1b48c25a arm: dts: qcom: db410c: Enable USB OTG support
fb3832787df1 phy: qcom-usb-hs: Fix unbalanced notifier registration
ed0628fbc330 usb: chipidea: Fix otg event handler
1c164955ea22 usb: chipidea: Prevent unbalanced IRQ disable
d819d86175e9 doc: usb: ci-hdrc-usb2: Add pinctrl properties definition
9fda0b18729d usb: chipidea: Add dynamic pinctrl selection
0540174cb689 arm64: defconfig: Enable PM8916 watchdog driver
02aaff80f217 arm64: dts: qcom: pm8916: Add PON watchdog node
1cdd7c9f2f11 dt-bindings: watchdog: Add Qualcomm PM8916 …
> recipes-kernel/linux: Update to the latest release 4.14.90

- recipes-bsp/wcnss-config/wcnss-config_1.13.bb
Using tags in SRCREV would force bitbake to poke at remote repo all the
time since tags are floating pointers, therefore encode the
corresponding SHA to avoid build failures when NO_NETWORK is set
> wcnss-config: Do not use tag in SRCREV

- conf/machine/dragonboard-410c.conf
- conf/machine/include/qcom-apq8096.inc
Latest OE-Core removed the arch-armv8 tune file and added a new set of tune files cortex A cores.
@kraj another heads up.
> Update default tune configuration based on latest OE-Core

- recipes-kernel/linux-firmware/linux-firmware_git.bbappend
Downgrade to stable version of ath10k firmware for dragonboard820c,
RM.4.4.1.c2-00057-QCARMSWP-1 version is causing a HW reboot [1]
use RM.4.4.1-00079-QCARMSWPZ-1 instead.
A new version that fixed the problem is available [2] but not landed
linux-firmware yet.
[1] https://validation.linaro.org/scheduler/job/1906358#L2444
[2] https://github.com/kvalo/ath10k-firmware/blob/master/QCA6174/hw3.0/4.4.1/firmware-6.bin_WLAN.RM.4.4.1-00132-QCARMSWP-1
> recipes-kernel: Add linux-firmware_git.bbappend for dragonboard820c

- recipes-devtools/qdl/qdl_git.bb
Fixes build issues e.g.
| qdl.c:43:10: fatal error: 'libudev.h' file not found
| #include <libudev.h>
|          ^~~~~~~~~~~
/bin/sh: pkg-config: command not found
patch.c:33:10: fatal error: libxml/parser.h: No such file or directory
33 | #include <libxml/parser.h>
|          ^~~~~~~~~~~~~~~~~
> qdl: needs pkgconfig and udev

- recipes-kernel/linux/linux-linaro-qcomlt_5.2.bb
Change,
b13017c21d43 arch/arm64/*/defconfig: Configure USB_XHCI_{PCI, HCD} as a module
> recipes-kernel/linux: Bump DB845c 5.2 kernel to b13017c21d

- recipes-devtools/qdl/files/0001-Makefile-Use-pkg-config-for-libxml2-detection.patch
This is because of LDFLAGS and CFLAGS being overwritten in Makefile as a
result we missing hash-style option
see
https://errors.yoctoproject.org/Errors/Details/267081/
> qdl: Fix QA Issue: No GNU_HASH in the ELF binary

- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
> recipes-bsp/firmware: Bump dragonboard845c firmware to v4 release

- conf/machine/dragonboard-410c.conf
New bootloader comes with new partitions to store rmtfs firmware [1].
[1] https://git.linaro.org/landing-teams/working/qualcomm/db-boot-tools.git/commit/?id=04008fd6570b566041e6ded5df738068416607e3
> conf/machine: Update rootfs partition in dragonboard-410c

- recipes-support/tqftpserv/tqftpserv/0001-include-limits.h-for-PATH_MAX.patch
- recipes-support/tqftpserv/tqftpserv_git.bb
Proposed upstream see
https://github.com/andersson/tqftpserv/pull/4
but I wonder if such recipes should be in meta-oe and not stashed into  BSP layers
> tqftpserv: Fix build on musl

- conf/machine/dragonboard-410c.conf
This change has been applied to other branches already. Applying it in Sumo will enable LKFT builds to use the new partition table on the LAVA devices that bear that tag.
> [sumo] Cherry-pick update to rootfs partition in dragonboard-410c

- recipes-kernel/linux/linux-linaro-qcomlt_5.4.bb
Changes,
37a87299c862 distro.config: Enable OV5640 and OV5645 drivers
7a62aa18349e arm64: defconfig: Enable QCOM CAMSS and CCI drivers
4a61ef69c042 arm64: dts: apq8016-sbc: Add camera cci/sensor nodes
837e4f15505a arm64: dts: msm8916: Add CCI node
4a3cf895cab7 dt-bindings: i2c: Add binding for Qualcomm CCI I2C controller
334988bca574 i2c: Add Qualcomm CCI I2C driver
628ec7ef3004 media: ov5640: add PIXEL_RATE control
> recipes-kernel: Linux 5.4 bump to 37a87299c862

- recipes-kernel/linux/linux-linaro-qcomlt_5.4.bb
Fixes,
447814278e3f remoteproc: qcom: wcnss: Add iris completion barrier
> recipes-kernel/linux: Linux 5.4 bump to rev 447814278e3f

- recipes-test/images/initramfs-test-image.bb
Add bluez package to allow validation of bluetooth support, pciutils to
get lspci, pd-mapper and tqftpserv to allow booting the WiFi firmware,
usbutils for lsusb and wpa-supplicant to allow basic testing of the
WiFi support.
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
> initramfs-test-image: Add useful utilities for testing

- recipes-test/images/initramfs-test-image.bb
> recipes-test/images: Add dhcp to initramfs-test-image

- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
Changes,
ba75ed77ea9e Merge tag 'v5.7.2' into release/qcomlt-5.7
8b0853ff4472 Merge branch 'tracking-qcomlt-lt9611' into release/qcomlt-5.7
8ee534ec8a56 drm/bridge: Introduce LT9611 DSI to HDMI bridge
7636286afbd1 dt-bindings: display: bridge: Add documentation for LT9611
9250431bb3b5 dt-bindings: vendor-prefixes: Add Lontium vendor prefix
> recipes-kernel: Linux 5.7 bump to 5.7.2 (ba75ed77ea9e)

- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
Changes,
a7ce3355155d Merge tag 'v5.7.3' into release/qcomlt-5.7
...
9aff2dcc27eb wcn36xx: Fix multiple AMPDU sessions support
44e6ad37e04a wcn36xx: Add ieee80211 rx status rate information
> recipes-kernel: Linux 5.7 bump to 5.7.3 (a7ce3355155d)

- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
Changes,
37b31489130d wcn36xx: Fix software-driven scan
9e5c701f0dc6 wcn36xx: Advertise beacon filtering support in bmps
f0076ecebddf mac80211: Do not report beacon loss if beacon filtering enabled
d5ffda0bd43b Merge tag 'v5.7.5' into release/qcomlt-5.7
> recipes-kernel: Linux 5.7 bump to 5.7.5 (37b31489130d)

- recipes-kernel/linux-firmware/linux-firmware_%.bbappend
The linux-firmware package complains that venus fw is supplied by both
linux-firmware and firmware-qcom-dragonboard845c. The venus firmware
supplied by linux-firmware is broken. This patch removes the installed
files for venus-5.2 and venus-5.4 which is not explicitly listed in
the linux-firmware recipe from openembedded.
The linux-firmware recipe is actually ambiguous in the sense that it doesn't
list the venus-5.2 package in the recipe, but does install it alongside all
the other firmware in the do_install part of the recipe.
Collected errors:
check_data_file_clashes: Package linux-firmware wants to install file /workdir/build/tmp-glibc/work/dragonboard_845c-linux/rb3-image-dev/9999.1-r0/rootfs/lib/firmware/qcom/venus-5.2/venus.b00
But that file is already provided by package * …
> Remove broken venus-5.2 and venus-5.4 from linux-firmware

- conf/machine/qrb5165-rb5.conf
- recipes-kernel/linux/linux-linaro-qcomlt-5.7/0001-arm64-dts-qcom-sm8250-Add-USB-and-PHY-device-nodes.patch
- recipes-kernel/linux/linux-linaro-qcomlt-5.7/0001-arm64-dts-qcom-sm8250-Add-support-for-SDC2.patch
- recipes-kernel/linux/linux-linaro-qcomlt-5.7/0001-arm64-dts-qcom-sm8250-Rename-UART2-node-to-UART12.patch
- recipes-kernel/linux/linux-linaro-qcomlt-5.7/0001-arm64-dts-qcom-sm8250-add-I2C-and-SPI-nodes.patch
- recipes-kernel/linux/linux-linaro-qcomlt-5.7/0001-arm64-dts-qcom-sm8250-change-spmi-node-label.patch
- recipes-kernel/linux/linux-linaro-qcomlt-5.7/qrb5165-rb5-enable.patch
- recipes-kernel/linux/linux-linaro-qcomlt-5.7/qrb5165-rb5.dts
- recipes-kernel/linux/linux-linaro-qcomlt-dev.bb
- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
Add initial support for Qualcomm RB5 robotics platform:
- machine config,
- dts tree support for 5.7 kernel,
- new linux-linaro-qcomlt-dev recipe tracking latest integration tree.
> RB5 support

- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
Changes,
21bb88052948 venus: firmware: Set virtual address ranges
2d8435ad822f firmware: qcom_scm: Add memory protect virtual address ranges
4130227f0f7e Merge tag 'v5.7.7' into release/qcomlt-5.7
fb6c79052380 Linux 5.7.7
> recipes-kernel: Linux 5.7 bump to 5.7.7 (21bb88052948)

- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
Summary,
* Point update to 5.7.19.
* Fixes on venus encoder and boot on DB820c (msm8996).
Changes,
4af49ea41ecf1 Merge tag 'v5.7.19' into release/qcomlt-5.7
...
0251e67cac68e media: venus: Fix reported frame intervals
565814f2abdb9 Merge tag 'v5.7.12' into release/qcomlt-5.7
...
9f6b67115e558 Merge tag 'v5.7.11' into release/qcomlt-5.7
...
2800aaa3b8bfb arm64: dts: qcom: msm8996: Reduce vdd_apc voltage
f0d61fa89bed5 Revert "arch: arm64: dts: msm8996: Change opp table compatible string"
> recipes-kernel: Linux 5.7 bump to 5.7.19 (4af49ea41ecf1)

- conf/machine/dragonboard-845c.conf
- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
- recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- recipes-test/images/initramfs-test-image.bb
A fix was add on mainline to support linux-firmware binary,
https://git.linaro.org/landing-teams/working/qualcomm/kernel.git/commit/?h=release/qcomlt-5.7&id=21bb88052948b35bdce926f301f2ba7970040812
> Use venus 5.2 from linux-firmware for DB845c and replace dhcp-client with dhcpcd

- conf/machine/qrb5165-rb5.conf
- recipes-bsp/firmware/.gitignore
- recipes-bsp/firmware/firmware-qcom-rb5_1.0.bb
Add recipe extracting firmware files from Qualcomm's binary releases and
packaging them into proper binary package.
> firmware-qcom-rb5: package QRB5165 RB5 firmware files

- conf/machine/qrb5165-rb5.conf
QRB5165 RB5 machine config lists sda15 as rootfs, which is C&P from
SM8250-MTP. Use sda6 as rootfs (which is proper userdata on RB5).
> qrb5165-rb5: correct rootfs (userdata) partition

- recipes-bsp/firmware/firmware-qcom-dragonboard410c-bootloader-sdcard_17.09.bb
- recipes-bsp/firmware/firmware-qcom-dragonboard410c_1034.2.1.bb
- recipes-bsp/firmware/firmware-qcom-dragonboard820c_01700.1.bb
- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
- recipes-bsp/firmware/firmware-qcom-rb5_1.0.bb
- recipes-bsp/firmware/firmware-qcom-sd-600eval_1.0.bb
- Remove COMPATIBLE_MACHINE to allow be installed in any machine.
- Remove conflicts with linux-firmware-qcom-license:
When try to install together this tree packages fails due to each of
them provide license so use linux-firmware one since we are using
linux-firmware when available.
- Install each license with ${PN} suffix to avoid install
conflicts.
> recipes-bsp/firmware: Compatible machine and License install

- recipes-graphics/mesa/mesa_git.bb
Mesa has .gitlab-ci folder that contains scripts and fail/skips useful
in order to run tests.
> recipes-graphics: Add package in mesa-dev to install CI files

- recipes-bsp/firmware/firmware-qcom-sd-600eval_1.0.bb
Fixes
ERROR: QA Issue: File '/lib/firmware/dsps.b00' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/dsps.mdt' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/gss.b00' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/gss.mdt' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
ERROR: QA Issue: File '/lib/firmware/mobicore.b00' from firmware-qcom-sd-600eval was already stripped, this will prevent future debugging! [already-stripped]
Signed-off-by: Khem …
> firmware-qcom-sd-600eval: Skip checking for already stripped binaries

- recipes-bsp/firmware/firmware-qcom-sd-600eval_1.0.bb
Fixes errors like
firmware-qcom-sd-600eval: /lib/firmware/a225_pfp.fw is owned by uid 1000, which is the same as the user running bitbake. This may be due to host contamination
> firmware-qcom-sd-600eval: Replace cp -a with proper options

- conf/machine/qrb5165-rb5.conf
Now let's get it right. Userdata partition on RB5 is sda8, not sda6.
sda6 is system_a:
1               6               7   8.0 KiB     A02C  ssd
2               8            8199   32.0 MiB    A026  persist
3            8200            8455   1024.0 KiB  A01F  misc
4            8456            8583   512.0 KiB   A02D  keystore
5            8584            8711   512.0 KiB   FFFF  frp
6            8712         8397319   32.0 GiB    A038  system_a
7         8397320        16785927   32.0 GiB    FFFF  system_b
8        16785928        29595642   48.9 GiB    A03A  userdata
> qrb5165-rb5: Correct userdata partition on RB5

- recipes-kernel/linux/linux-linaro-qcomlt_5.9.bb
RB5 boards are not fully supported by the main release 5.7 kernel, so
add separate version built from RB5-specific release branch.
> linux: add linux-linaro-qcomlt_5.9.bb kernel for RB5

- recipes-bsp/firmware/files/lib-firmware-modem.service
- recipes-bsp/firmware/files/lib-firmware-system.service
- recipes-bsp/firmware/firmware-qcom-rb5_1.0.bb
This PR enables using pre-flashed partitions (modem_a, system_a) to get firmware files. Unfortunately this has to be started early (before) udev, so it is neither possible to use mount units (as systemd does not know about block devices yet) nor possible to use meaningful names (/dev/block/by-partlabel/FOO).
> Mount RB5 partitions to get firmware

- recipes-graphics/mesa/files/0001-src-util-disk_cache_os.c-Add-missing-headers-for-ope.patch
- recipes-graphics/mesa/files/fix-meson-config-compat.patch
- recipes-graphics/mesa/mesa_git.bb
Latest mesa rev 3424e17b9a9beca85c0ef60e195eb544faea8995 broke the
build.
- Update fix-meson-config-compat.patch patch to add broadcom target.
- Add 0001-src-util-disk_cache_os.c-Add-missing-headers-for-ope.patch to
fix musl build, submitted to [1].
[1] https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7146.
> recipes-graphics: Fix mesa-git build

- recipes-kernel/linux/linux-linaro-qcomlt_5.9.bb
> recipes-kernel: Add Linux 5.9 support for apq8016|apq8096|sdm845

- recipes-kernel/linux/linux-linaro-qcomlt_5.9.bb
No Landing team changes only v5.9.2..v5.9.6 window.
> recipes-kernel: Linux 5.9 (apq8016|apq8096|sdm845) bump to v5.9.6

- recipes-test/diag/diag/0001-Disable-use-of-__NR_io_getevents-when-not-defined.patch
- recipes-test/diag/diag_git.bb
rv32 does not have __NR_io_getevents syscall due to it using 64bit time_t
therefore make code use it only when its provided by architecture
> diag: Fix build on riscv32

- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
> linux-linaro-qcomlt: bump 5.10 SRCREV to get CAN driver enabled

- recipes-support/rmtfs/rmtfs_git.bb
Fixes,
1cc12d3 storage: Use storage_close() to free up resources on exit
bf5cb9f rproc: Make start & stop threads detached
30f5dfb rproc: NUL-terminate the modalias
8a1d24a rproc: Make state update errors more helpful
> recipes-support: rmtfs bump to rev 1cc12d3

- recipes-bsp/firmware/files/lib-firmware-system.service
As a followup to 5cdb497e1b99 ("qrb5165-rb5.conf: switch to using
PARTLABEL=userdata for rootfs") use sda7 as system partition holding
a650 firmware.
> firmware-qcom-rb5: use sda7 instead of sda6 as the system partition

- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/0001-ath10k-bdencoder-Switch-to-python3.patch
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/0002-ath10k-bdencoder-Add-option-to-switch-to-ath11k-mode.patch
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife_git.bb
On RB5 ath11k module requires board data not present in linux-firmware archive. Add support for generating it at build time.
> Separate qca-swiss-army-knife from firmware-qcom-dragonboard845c

- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/0001-read-powers-port-to-python3.patch
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/0002-ath10k-fwencoder-port-to-python3.patch
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/0003-scripts-port-to-python3.patch
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife_git.bb
Fix following QA issues in qca-swiss-army-knife packages:
```
ERROR: QA Issue: /usr/bin/ath10k-bdencoder contained in package qca-swiss-army-knife requires /usr/bin/python3, but no providers found in RDEPENDS_qca-swiss-army-knife? [file-rdeps]
ERROR: QA Issue: /usr/bin/read-powers contained in package qca-swiss-army-knife requires /usr/bin/python, but no providers found in RDEPENDS_qca-swiss-army-knife? [file-rdeps]
ERROR: QA Issue: /usr/bin/irq-watch contained in package qca-swiss-army-knife requires /usr/bin/perl, but no providers found in RDEPENDS_qca-swiss-army-knife? [file-rdeps]
```
> Fix QA issues in qca-swiss-army-knife packages

- conf/machine/qrb5165-rb5.conf
- recipes-bsp/firmware/firmware-qcom-rb5_1.0.bb
- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
- recipes-kernel/linux/linux-qcom-bootimg.inc
Two patches to fix WiFi on RB5 board. Note, firmware files are not provided by this PR, they will come separately.
> Enable WiFi on RB5

- conf/machine/qrb5165-rb5.conf
While we are waiting for lt9611uxc firmware to be accepted into
linux-firmware repo, bbappend respective recipe to download and install
lt9611uxc firmware file.
> linux-firmware: install lt9611uxc firmware

- conf/machine/qrb5165-rb5.conf
- recipes-bsp/firmware/firmware-qcom-rb5_1.0.bb
- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
- recipes-kernel/linux/linux-qcom-bootimg.inc
Backport WiFi support for RB5 to dunfell branch. As we require linux-firmware backport, use next version.
> Backport WiFi support on RB5

- recipes-test/images/initramfs-test-image.bb
Add iw package to initramfs-test-image to supplement wpa-supplicant and
to allow controlling of the wifi devices.
> initramfs-test-image: add iw package

- conf/machine/qrb5165-rb5.conf
The ath11k driver fails to start the device properly if regdb can not be
loaded. Add wireless-regdb-static to MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS
if wifi is enabled in DISTRO_FEATURES to make sure all images are able
to bootstrap the onboard QCA6390 (ath11k) device.
> qrb5165-rb5.conf: add wireless-regdb-static to RRECOMMENDS

- conf/machine/qrb5165-rb5.conf
(cherry picked from commit 78d549d0f0f4497df9b9b59bf06dfbcf6fcd986e)
> qrb5165-rb5.conf: enable linux-firmware-lt9611uxc

- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
- recipes-kernel/linux/linux-linaro-qcomlt_5.9.bb
When renesas firmware loader landed upstream [1] there is a common name
for the firmware so install the K2026090.mem as renesas_usb_fw.mem.
[1] https://github.com/torvalds/linux/commit/a66d21d7dba84deeaf3b296c43eafc11094b6f09
> recipes-bsp: firmware-qcom-dragonboard845c fix installation of renesas

- recipes-kernel/linux/linux-linaro-qcomlt_5.9.bb
Changes,
b5ff44498a19 Merge tag 'v5.9.16' into release/qcomlt-5.9
f6bb36622ffd usb: renesas-xhci: Revert "usb: renesas-xhci: remove version check
...
> recipes-kernel/linux: Linux 5.9 db{410,845}c bump to rev b5ff44498a19

- recipes-graphics/mesa/files/0001-meson.build-check-for-all-linux-host_os-combinations.patch
- recipes-graphics/mesa/files/0002-meson.build-make-TLS-ELF-optional.patch
- recipes-graphics/mesa/mesa_git.bb
Refresh patches to apply,
0001-meson.build-check-for-all-linux-host_os-combinations.patch
0002-meson.build-make-TLS-ELF-optional.patch
> recipes-graphics: mesa_git bump to rev eb2a4a7dee

- recipes-support/fastrpc/fastrpc_git.bb
Default fastrpc listeners should be packaged as a part of fastrpc
package (rather than fastrpc-dev), where they land by default.
The patch `0001-src-Makefile.am-simplify-build-template.patch` is pending review by Srini.
> fastrpc: fix packaging of default listeners

- recipes-graphics/mesa/mesa_20.3.0-rc2.bb
Having DEFAULT_PREFERENCE_sm8250 = "1" would enforce using this recipe
(20.3.0-rc2) for sm8250 boards. Set this to the empty string instead as
a way to be able to override DEFAULT_PREFERENCE = "-1" for sm8250, but
still use newer versions as they are available now.
> mesa: do not enforce preference for sm8250

- recipes-support/fastrpc/fastrpc_git.bb
Default fastrpc listeners should be packaged as a part of fastrpc
package (rather than fastrpc-dev), where they land by default.
(cherry picked from commit 50c0e0b7fdbf8d3efb50f7edb6b5d6bf008d21c8)
> fastrpc: bump srcrev and fix packaging of default listeners

- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
Changes,
a58febc453b5 arch/arm64/configs/defconfig: Enable USB_DWC3_ULPI for db820c
23c320329d2e arm64: defconfig: Enable PM8916 watchdog driver
775d8cfc20a4 arch/arm64/configs/defconfig: enable POWER_RESET_QCOM_PON
5fbc47cc611a arm64: defconfig: Enable fastrpc, mailbox
c1c8cba7b722 arch/arm64/configs/defconfig: Enable BT_QCOMSMD as m for db410c
14d381093d5d ASoC: qcom: Fix broken support to MI2S TERTIARY and QUATERNARY
e2f02a85415a ASoC: hdmi-codec: Fix return value in hdmi_codec_set_jack()
> recipes-kernel: Linux 5.10 bump to rev a58febc453b5

- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
Bump SRCREV to use new firmware names on RB5 board (use squashed .mbn
files instead of .mdt files).
> linux-linaro-qcomlt_5.10: bump SRCREV to fix firmware names on RB5

- recipes-multimedia/alsa/alsa-ucm-conf/0001-ucm2-codecs-lpass-add-codec-sequences-for-wsa-and-va.patch
- recipes-multimedia/alsa/alsa-ucm-conf/0002-ucm2-add-support-to-for-Qualcomm-RB5-Platform.patch
- recipes-multimedia/alsa/alsa-ucm-conf/0003-ucm.conf-support-KernelModule-CardLongName.conf-path.patch
- recipes-multimedia/alsa/alsa-ucm-conf/0004-module-add-new-symlink-for-Qualcomm-sdm845-driver.patch
- recipes-multimedia/alsa/alsa-ucm-conf/0007-ucm2-module-add-snd_soc_sm8250-symlink.patch
- recipes-multimedia/alsa/alsa-ucm-conf_%.bbappend
Refresh patches adding support for RB5 platform. As we are at it, move
data to new place (Qualcomm/sm8250) and put symbolic links necessary to
load it.
> alsa-ucm-conf: refresh qrb5165-rb5 patches

- recipes-kernel/linux/linux-linaro-qcomlt_5.11.bb
For the next RB5 release add 5.11 linux-linaro-qcomlt recipe using
special release branch.
> linux-linaro-qcomlt: add 5.11 version for sm8250 (RB5)

- recipes-graphics/mesa/mesa_git.bb
Fixes deqp freedreno installation paths changed in rev
6d2afe1c832.
https://gitlab.freedesktop.org/mesa/mesa/-/commit/6d2afe1c83254c4cf437e14a221087ecc01cc7d1
> recipe-graphics: mesa_git bump to rev 13f92183c7d

- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
Changes,
9ab492e76768 arm64: defconfig: Enable QCOM audio as modules
67cf276de670 misc: fastrpc: restrict user apps from sending kernel RPC messages
b8ff783ddc4f misc: fastrpc: fix incorrect usage of dma_map_sgtable
fb0392de9ea6 arm64: dts: qcom: qrb5165-rb5: switch into using GPIO for SPI0 CS
00431b42fbd7 arm64: dts: qcom: sm8250: add pinctrl for SPI using GPIO as a CS
e207855faec3 spi-geni-qcom: fix spi_geni_transfer_one for SE case
> recipes-kernel: Linux 5.10 bump to rev fb0392de9ea6

- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
Changes,
9ab492e76768 arm64: defconfig: Enable QCOM audio as modules
67cf276de670 misc: fastrpc: restrict user apps from sending kernel RPC messages
b8ff783ddc4f misc: fastrpc: fix incorrect usage of dma_map_sgtable
fb0392de9ea6 arm64: dts: qcom: qrb5165-rb5: switch into using GPIO for SPI0 CS
00431b42fbd7 arm64: dts: qcom: sm8250: add pinctrl for SPI using GPIO as a CS
e207855faec3 spi-geni-qcom: fix spi_geni_transfer_one for SE case
(cherry picked from commit 8a1f863618a6e56ae4e0b894cde5116c3f5d27cf)
> recipes-kernel: Linux 5.10 bump to rev 9ab492e76768

- recipes-kernel/linux/linux-linaro-qcomlt_5.11.bb
Bump SRCREV to include Linus'es 5.11 release.
> linux-linaro-qcomlt_5.11: bump SRCREV to 5.11 release

- recipes-kernel/linux/linux-linaro-qcomlt_5.11.bb
Bump SRCREV to include Linus'es 5.11 release.
(cherry picked from commit 45eb29f610d7508a4fdd4d19312b886085f6f885)
> linux-linaro-qcomlt_5.11: bump SRCREV to 5.11 release (dunfell)

- recipes-kernel/linux/linux-linaro-qcomlt-dev.bb
This kernel recipe builds the QCLT integration branch which is not a
*relase* branch, but is regularly rebased. With a fixed SRCREV the
build will often break. Instead let's use AUTOREV. While it's not
recommended, DEFAULT_PREFERENCE will ensure that this recipe is not
used unless it's explicitely required.
> recipes-kernel/linux/linux-linaro-qcomlt-dev: use AUTOREV

- recipes-multimedia/alsa/alsa-ucm-conf/0001-ucm2-Separate-the-configuration-lookups-hw-based-fro.patch
Fixes cd7a3371bb92 (alsa-ucm-conf: add patches to lookup config using
kernel driver name). The patch file added in the bbappend is missing,
and build fails.
> alsa-ucm-conf: add missing patch

- recipes-kernel/linux/linux-linaro-qcomlt_5.10.bb
Changes,
6afb1155f01d venus: pm_helpers: Set opp clock name for v1
893d70f9ddce venus: hfi_parser: Don't initialize parser on v1
97e75989b610 thermal: cpufreq_cooling: freq_qos_update_request() returns < 0 on error
4aec9d8fb1a1 arm64: defconfig: Enable missing QCOM interconnect drivers
> recipes-kernel: Linux 5.10 bump to 6afb1155f01d

- recipes-graphics/mesa/mesa_git.bb
Small change docs: Xorg -> X.Org in upstream, see,
https://gitlab.freedesktop.org/mesa/mesa/-/commit/2f42c21221cf89f738225e3ac2aa2e85953c1dc1
> recipes-graphics: mesa_git update license chcksum

- conf/machine/qcom-armv8a.conf
- conf/machine/qrb5165-rb5.conf
Latest RB5 bootloader package provides updated partition scheme. It
removes Android partitions and adds single rootfs partition at
/dev/sda1. Switch to new rootfs partition.
> qrb5165-rb5: use new rootfs partition

- recipes-kernel/linux/linux-linaro-qcomlt_5.12.bb
Update SRCREV to include Venus firmware filename fix.
> linux-linaro-qcomlt_5.12: update SRCREV

- conf/layer.conf
meta-qcom depends only oe-core, mark it explicitely. The layer has
additional dependencies on meta-oe or meta-networking, but they are
optional.
> layer.conf: set LAYERDEPENDS

- conf/machine/dragonboard-820c.conf
To install qca/nvm_00440302.bin required for bluetooth.
> conf/machine: Add linux-firmware-qca for dragonboard-820c

- recipes-graphics/mesa/files/0001-meson-misdetects-64bit-atomics-on-mips-clang.patch
- recipes-graphics/mesa/files/0001-meson.build-check-for-all-linux-host_os-combinations.patch
- recipes-graphics/mesa/files/0002-meson.build-make-TLS-ELF-optional.patch
- recipes-graphics/mesa/files/0003-Allow-enable-DRI-without-DRI-drivers.patch
- recipes-graphics/mesa/files/0004-Revert-mesa-Enable-asm-unconditionally-now-that-gen_.patch
- recipes-graphics/mesa/mesa_git.bb
- Update branch name to main.
- Update PV to 2x.x-dev recently mesa bump to 21.x versions so use 2x.x
for our mesa_git dev build.
- Refresh patches to avoid warnings when apply.
> recipes-graphics: mesa_git update to rev 26677008b9a

- recipes-bsp/lt9611uxc-upgrade/lt9611uxc-upgrade/lt9611uxc-upgrade.sh
Update script to only execute cat in directories where lt9611uxc_firmware
exists.
On my system both module and 5-002b are symbolic links, thus the previous
script would cause the lt9611uxc firmware update systemd unit to fail because
the script would try to access lt9611uxc_firmware in the module directory and
return a failure which would cause the systemd service to be listed under
'systemctl list-units --failed'
Signed-off-by: Olivier Schonken <olivier.schonken@gmail.com>
> lt9611uxc-upgrade script: Only cat firmware version when it exists

- recipes-support/fastrpc/fastrpc_git.bb
The tip-of-tree fastrpc has had an updated applied such that it is possible
when running `bitbake rpb-desktop-image -c populate_sdk` to now populate
fastrpc headers into the resulting x-compiler.
Results in rpb-x86_64/sysroots/armv8-2a-linaro-linux/usr/include/fastrpc/
Signed-off-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org>
> fastrpc: Update to latest SRCREV for SDK headers

- recipes-graphics/mesa/files/0001-meson-misdetects-64bit-atomics-on-mips-clang.patch
- recipes-graphics/mesa/files/0001-meson.build-check-for-all-linux-host_os-combinations.patch
- recipes-graphics/mesa/files/0002-meson.build-make-TLS-ELF-optional.patch
- recipes-graphics/mesa/files/0003-Allow-enable-DRI-without-DRI-drivers.patch
- recipes-graphics/mesa/files/0004-Revert-mesa-Enable-asm-unconditionally-now-that-gen_.patch
- recipes-graphics/mesa/mesa_git.bb
The deqp skips file was renamed, see,
https://gitlab.freedesktop.org/mesa/mesa/-/commit/9cc1f089196f2f5c695dbf5f42b947b9970b8965
> recipes-graphics: mesa_git refresh patches and fix deqp filename

- recipes-support/rmtfs/rmtfs_git.bb
Change,
293ab8b storage: Sync changes
> recipes-support: rmtfs bump to rev 293ab8b

- conf/machine/include/qcom-common.inc
The SERIAL_CONSOLES var is used inside systemd-serialgetty.bb to
generate systemd unit to get console after boot, this fix no console in
DB845c.
(cherry picked from commit 40ae8d5b56422ef440b603d2e6713d8b577138ab)
> conf/machine: Set default SERIAL_CONSOLES in qcom-common.inc

- recipes-kernel/linux/linux-linaro-qcomlt_5.13.bb
Default configuration have been moved in the shared include file,
since 7829b0f0f691 (linux-linaro-qcomlt: move common settings to the
include file), so there is no need to repeat them in each new kernel
recipe.
> linux-linaro-qcomlt_5.13: remove default configs

- recipes-kernel/linux/linux-linaro-qcom.inc
Fixes: 7829b0f0f691 (linux-linaro-qcomlt: move common settings to the
include file)
In this commit, some common config were moved into the shared include
file, however LOCALVERSION was not updated based on its value in the
kernel recipe. Restore LOCALVERSION to what it was before this patch.
> linux-linaro-qcom: update LOCALVERSION

- recipes-kernel/linux/linux-linaro-qcomlt_5.13.bb
Changes are from stable v5.13.5..v5.13.6.
> recipes-kernel: Linux 5.13 bump to rev 9095a563c16e (v5.13.6)

- conf/layer.conf
- conf/machine/dragonboard-410c-32.conf
- conf/machine/dragonboard-820c.conf
- conf/machine/dragonboard-845c.conf
- conf/machine/include/qcom-common.inc
- conf/machine/qcom-armv8a.conf
- conf/machine/qrb5165-rb5.conf
- conf/machine/sm8250-mtp.conf
- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs_%.bbappend
- dynamic-layers/openembedded-layer/recipes-navigation/gpsd/gpsd_%.bbappend
- recipes-bsp/firmware/firmware-qcom-dragonboard410c.inc
- recipes-bsp/firmware/firmware-qcom-dragonboard820c_01700.1.bb
- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
- recipes-bsp/firmware/firmware-qcom-rb5_20210331-v4.bb
- recipes-bsp/firmware/firmware-qcom-sd-600eval_1.0.bb
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife_git.bb
- recipes-devtools/qdl/qdl_git.bb
- recipes-graphics/mesa/mesa_%.bbappend
- recipes-graphics/mesa/mesa_git.bb
- recipes-graphics/xorg-xserver/xserver-xf86-config_0.1.bbappend
- recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
- recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- recipes-kernel/linux/linux-linaro-qcom.inc
- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
- recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
- recipes-support/fastrpc/fastrpc_git.bb
- recipes-support/pd-mapper/pd-mapper_git.bb
- recipes-support/qrtr/qrtr_git.bb
- recipes-support/rmtfs/rmtfs_git.bb
- recipes-support/tqftpserv/tqftpserv_git.bb
The conversion was mostly automated with:
./scripts/contrib/convert-overrides.py
With a few manual tweaks.
Also change LAYERCOMPAT to honister.
> layer: convert to new override syntax

- recipes-kernel/linux/linux-linaro-qcomlt_5.13.bb
Changes are from stable v5.13.6..v5.13.9.
> recipes-kernel: Linux 5.13 bump to rev 473ca0b26c31 (v5.13.9)

- recipes-kernel/linux/linux-linaro-qcomlt_5.13.bb
Summary,
- Update LHM patches for RB3 because old ones causes crash when use
hackbench.
- Remove enablement of TYPEC_MUX_NB7VPQ904M not used in RB5 atm.
Changes,
1429722a2209 dt-bindings: thermal: Add dt binding for QCOM LMh
e59d36510fc7 arm64: dts: qcom: sdm845: Remove cpufreq cooling devices for CPU thermal zones
5313a150780d arm64: dts: qcom: sdm45: Add support for LMh node
0cdd72ea4ded cpufreq: qcom-cpufreq-hw: Add dcvs interrupt support
28c75f036f17 thermal: qcom: Add support for LMh driver
5249d7424534 firmware: qcom_scm: Introduce SCM calls to access LMh
79a4f0126f44 Revert "arm64: defconfig: Enable TYPEC_MUX_NB7VPQ904M for RB5"
d56d5568e63c Revert "dt-bindings: thermal: Add dt binding for QCOM LMh"
832f6e4b8290 Revert "arm64: boot: dts: qcom: sdm845: Remove cpufreq cooling devices …
> recipes-kernel: Linux 5.13 bump to rev 1429722a2209

- conf/machine/include/qcom-sa8155p.inc
- conf/machine/sa8155p-adp.conf
- recipes-kernel/linux/linux-linaro-qcomlt_5.14.bb
Add configuration files for SA8155P-ADP board which
uses the SM8150 SoC.
Here we create an include (.inc) file and a configuration
(.conf) file for the adp board.
> conf/machine: Add initial support for SA8155P-ADP board

- dynamic-layers/openembedded-layer/recipes-test/images/initramfs-test-full-image.bbappend
- recipes-test/images/initramfs-test-full-image.bb
Add following utilities to 'initramfs-test-image.bb':
-> For kexec/kdump analysis:
- crash
- makedumpfile
- kexec
-> iozone3: for filesystem performance analysis.
-> cryptsetup: for crypto benchmarks.
-> util-linux: for 'gdisk', 'taskset', etc.
-> coreutils: mainly for 'dd' (as busybox 'dd' does not show performance
figures).
Addition of the above tools results in an approximate increase of
6M in the resulting rootfs size (cpio.gz archive)
Before:
-------
$ ls -lah initramfs-test-image-qcom-armv8a-20210521045425.rootfs.cpio.gz
19M
After:
------
$ ls -lah initramfs-test-image-qcom-armv8a-20210521070020.rootfs.cpio.gz
25M
> recipes-test: Add new utilities to 'initramfs-test-image.bb'

- dynamic-layers/networking-layer/recipes-test/images/initramfs-test-image.bbappend
- dynamic-layers/openembedded-layer/recipes-test/images/initramfs-test-image.bbappend
- recipes-kernel/linux/linux-qcom-bootimg.inc
- recipes-test/images/initramfs-kerneltest-image.bb
- recipes-test/images/initramfs-test-image.bb
- recipes-test/images/initramfs-tiny-image.bb
A version of #232 with `QCOM_BOOTIMG_BUNDLE_INITRAMFS` removed.
> Boot image with the bundled initramfs support

- conf/machine/sa8155p-adp.conf
Add the missing 'MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS'
directive in sa8155p-adp.conf
> conf/sa8155p-adp: Add kernel-modules

- conf/machine/sa8155p-adp.conf
Set INITRAMFS_IMAGE as "initramfs-kerneltest-full-image"
for sa8155p machine .
> layer.conf: set INITRAMFS_IMAGE for sa8155p machine

- recipes-test/images/initramfs-test-full-image.bb
Add the following utilities in 'initramfs-test-full-image.bb'
- hdparm (for performance checks - e.g. USB mass storage related)
- mbw, dhrystone, lmbench, sysbench, tinymembench, tiobench, whetstone
(for performance checks).
- Add kexec instead of the complete 'kexec-tools'
> initramfs-test-full: Add more utils

- recipes-bsp/firmware/firmware-qcom-rb5_20210331-v4.bb
Remove obsolete comment mentioning NHLOS_URI and ADRENO_URI.
> firmware-qcom-rb5: remove obsolete comment

- recipes-test/images/initramfs-test-full-image.bb
Add 'util-linux-lsblk' in 'initramfs-test-full-image.bb',
which provides 'lsblk' utility.
> initramfs-test-full: Add util-linux-lsblk

- recipes-test/bootrr/bootrr/bootrr-auto-switch-to-using-sh.patch
- recipes-test/bootrr/bootrr_git.bb
- recipes-test/images/initramfs-test-full-image.bb
This is a RFC patch which allows adding bootrr to the meta-qcom layer as a receipes-test component.
To do:
- I am using my github tree as the SRC_UI, instead of Bjorn's official tree as PR raised against the bootrr tree is still under review <https://github.com/andersson/bootrr/pull/38>
- SRCBRANCH, etc should also be changed in the final version of this patch to point to the 'bootrr/master' branch.
I tested the resulting bootrr board helper files on sm8150-mtp and sa8155-adp boards with this change by running them as-
> Add bootrr to meta qcom

- conf/machine/dragonboard-410c-32.conf
- conf/machine/dragonboard-410c.conf
- conf/machine/dragonboard-820c.conf
- conf/machine/dragonboard-845c.conf
- conf/machine/qcom-armv8a.conf
- conf/machine/qrb5165-rb5.conf
- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard410c.bb
- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard820c.bb
- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard845c.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb5.bb
- recipes-test/images/initramfs-firmware-image.bb
To remove duplication between qcom-armv8a and other board files and to ease using firmware configuration in e.g. initramfs images create per-board firmware packagegroups.
> Per-board firmware packagegroups

- recipes-graphics/mesa/mesa_git.bb
The deqp-all-skips.txt was renamed to all-skips.txt, see:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/38dff02bfb1f237ded1e2075e560ec06b52fadcf
> recipes-graphics: mesa_git fix installation of new all-skips.txt

- recipes-test/bootrr/bootrr_git.bb
- recipes-test/diag/diag_git.bb
The default branch name for new repositories created on GitHub is now
main. While it does not affect existing repo, let's be more explicit
just in case, as there is uncertainty about how it will be managed in
general.
Also Github has announced that it will stop supporting git:// protocol
in Q1 2022, let's make sure we don't use it anymore, and use
https:// instead.
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
> bootrr, diag: make sure branch and protocol are configured

- recipes-test/images/initramfs-test-full-image.bb
this is undefined behaviour, mant times devs used them together to get
the missing space at the beginning of string which append/prepend needs
but thats not intended behaviour
> initramfs-test-full-image: Do not use append with += operator

- recipes-bsp/firmware/firmware-wcn6855_git.bb
Firmware for the WCN6855 is not yet provided in the linux-firmware.
Until it is provided by the linux-firmware, package it separately.
> firmware-wcn6855: provide firmware for wcn6855 wifi chip

- recipes-test/images/initramfs-test-full-image.bb
- recipes-test/images/initramfs-test-image.bb
- recipes-test/images/initramfs-tiny-image.bb
- remove duplication between `test` and `test-full` images
- handle `PACKAGE_INSTAL_foo-layer` automatically rather than listing them manually.
> Rework initramfs-test-image family of images

- recipes-kernel/linux/linux-linaro-qcomlt-dev.bb
- recipes-kernel/linux/linux-linaro-qcomlt-dev/0001-Revert-kbuild-Enable-DT-schema-checks-for-.dtb-targe.patch
There is no need to check dtb schema while building OE kernel images.
Not to mention that supporting dtschema properly requires significant
changes to the OE-core layer (which are still pending). With all that in
mind revert the commit making dtschema validation mandatory when
building individual dtb files.
Revert the patch here rather than in the integration tree itself, so
that users of the integration tree still can benefit from enforced dt
schema validation.
> linux-linaro-qcomlt-dev: revert dtschema enforced enabling

- recipes-devtools/debugcc/debugcc_git.bb
The debugcc tool can be useful on the target platforms. Add a recipe to
build corresponding package.
> debugcc: package Bjorn's debugcc tool

- recipes-bsp/firmware/firmware-qcom-dragonboard410c.inc
- recipes-bsp/firmware/firmware-qcom-dragonboard820c_01700.1.bb
- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
- recipes-bsp/firmware/firmware-qcom-nexus7-2013.bb
- recipes-bsp/firmware/firmware-qcom-rb5_20210331-v4.bb
- Simplify scripts by using FW_QCOM_PATH
- Follow upstream changes to use apq8016/apq8096 instead of msm8916/msm8996
- Package slpi firmware for the db845c.
> Update firmware packages

- recipes-kernel/linux/linux-linaro-qcomlt_5.15.bb
Changes,
43aa1d1f5fcf Merge tag 'v5.15.6' into HEAD
...
485c2c5a3cce drivers/net/wireless/ath: ath11k wmi restore mgmt_rx_event_params.chan_freq
> recipes-kernel: Linux 5.15 bump to rev 43aa1d1f5fcf (v5.15.6)

- conf/machine/sdx55-mtp.conf
- conf/machine/sdx55-telit-fn980.conf
There is enough upstream support for sdx55, we no longer need to use a
custom kernel recipe.
> sdx55: switch to main linux-linaro-qcoml kernel recipe

- conf/machine/sa8155p-adp.conf
Since we use the rpb-console* images for sa8155p machine now,
let's not set the INITRAMFS_IMAGE as "initramfs-kerneltest-full-image"
for sa8155p machine now.
> conf/sa8155p-adp.conf: Don't set INITRAMFS_IMAGE for sa8155p machine

- recipes-test/images/initramfs-test-image.bb
Add the following utilities to 'initramfs-test-image'
to allow easier board development:
- dropbear (for ssh and scp services),
- strace (qcom requested this to be added to allow tracing kernel func
calls),
- phytool (allows ethernet phy registers to be read / write).
This causes the initramfs-test-image.rootfs.cpio.gz size to be increased
by 0.5M.
(cherry picked from commit 9724a4e9acad343781b1e1997d43b37d1c06bc19)
> initramfs-test-image: Add a few utils

- recipes-kernel/linux/linux-linaro-qcomlt_5.16.bb
Update the SRCREV in linux-linaro-qcomlt_5.16.bb file
for sa8155p adp board, which now supports
additional ethernet fixes for kernel version 5.16.
> linux: Update SRCREV for release/sa8155p-adp/qcomlt-5.16

- recipes-test/images/initramfs-test-image.bb
Add lrzsz tool to be able to transfer files through the serial line.
The package uses 138 kiB of space.
> initramfs-test-image: enable lrzsz

- recipes-devtools/debugcc/debugcc_git.bb
The latest version of debugcc contains QCOM SM8450 SoC support.
Signed-off-by: Vladimir Zapolskiy <vladimir.zapolskiy@linaro.org>
> debugcc: bump package version

- recipes-kernel/linux/linux-linaro-qcomlt/0001-Revert-kbuild-Enable-DT-schema-checks-for-.dtb-targe.patch
- recipes-kernel/linux/linux-linaro-qcomlt_5.16.bb
Create a new .bb file for honister buils for sa8155p adp board
which already supports kernel version 5.16.
> linux: Add new .bb file for release/sa8155p-adp/qcomlt-5.16

- recipes-kernel/linux/linux-linaro-qcomlt_5.15.bb
- recipes-kernel/linux/linux-linaro-qcomlt_5.16.bb
Since honister is replacing dunfell as the more recent
stable branch, this change moves sa8155p-adp to the stable
kernel version 5.15.y and removes the 5.16 receipe.
Going forward, for sa8155p-adp board:
- dunfell would support 5.15.y stable kernel version, and
- honister would support kernel versions which are closer to
linus's tip.
> recipes-kernel: Move sa8155p-adp receipe to point to stable 5.15

- recipes-kernel/linux/linux-linaro-qcomlt_5.15.bb
Update the SRCREV in linux-linaro-qcomlt_5.15.bb file
for sa8155p adp board, which points to support for the following
new kernel features:
- PCIe0 in RC mode,
- LmH regulator,
- Crypto Engine support.
> linux: Update SRCREV for release/sa8155p-adp/qcomlt-5.15

- conf/machine/qcom-armv8a.conf
- conf/machine/qrb5165-rb5.conf
Mainline kernels do not provide `sm8250-rb5-dvt.dts`. Drop it from the default configuration. If necessary, this DTS can supported in `linux-linaro-qcom.inc`.
> Remove RB5 DVT support

- conf/layer.conf
- dynamic-layers/meta-linux-mainline/recipes-kernel/linux/linux-mainline.bbappend
- dynamic-layers/meta-linux-mainline/recipes-kernel/linux/linux-mainline.inc
- dynamic-layers/meta-linux-mainline/recipes-kernel/linux/linux-stable_%.bbappend
Add support for kernels from `meta-linux-mainline`. This allows using `linux-mainline` and `linux-stable` as providers for `virtual/kernel`.
> Linux mainline support

- recipes-kernel/images/initramfs-rootfs-image.bb
Exclude all the kernel images from this initramfs. This shrinks the
initramfs for a few megs.
> initramfs-rootfs-image: exclude all kernel images from the image

- recipes-kernel/images/initramfs-rootfs-image.bb
- recipes-support/initrdscripts/files/copy-modules.sh
- recipes-support/initrdscripts/initramfs-module-copy-modules_1.0.bb
Add an initramfs module that will copy modules from initramfs to the rootfs. To enable it, add 'copy_modules' kernel bootarg.
> Install modules into rootfs

- recipes-devtools/pil-squasher/pil-squasher_git.bb
Update pil-squasher to the latest revision to get elf64 squashing
capability.
> pil-squasher: update to the latest revision

- recipes-bsp/firmware/firmware-qcom-dragonboard820c_01700.1.bb
Add packages with modem firmware (mba.mbn, modem.mbn, modem.*).
It is confirmed that the modem boots on db820c. GNSS is still not
working.
> firmware-qcom-dragonboard820c: package modem firmware

- recipes-test/images/initramfs-test-image.bb
Enable several small utils to test i2c, sensors, cpufreq, to schedule
tasks to specific core and to get CPU features. This causes compressed
image growth of 254 KiB.
> initramfs-test-image: add several small utils

- recipes-test/images/initramfs-firmware-image.bb
As initramfs-firmware-image doesn't use the kernel modules, break the
dependency by setting KERNELDEPMODDEPEND to the empty strings.
> initramfs-firmware-image: remove kernel dependency

- recipes-test/images/initramfs-test-full-image.bb
Bundle gpsd and gps-utils into initramfs-test-image. This cause
compressed image growth of 1.6 MiB.
> initramfs-test-image: enable gpsd support

- recipes-test/images/initramfs-test-image.bb
To assist in checking EDID reads and modesetting enable the read-edid
package. The image growth is 9 KiB.
> initramfs-test-image: enable read-edid package

- recipes-kernel/linux/linux-linaro-qcomlt_5.15.bb
The following changes were backported from upstream:
090854301b471 scsi: ufs: ufs-qcom: Enter and exit hibern8 during clock scaling
adb54728a7a08 scsi: ufs: core: Export hibern8 entry and exit functions
> linux: update kernel for SA8155P-ADP

- README.md
The URIs provided in the README are not working anymore because:
* the unencrypted git protocol support has been removed from github [0]
* the OE core repository has changed name
This PR updates the README in order to provide valid URIs.
[0] https://github.blog/2021-09-01-improving-git-protocol-security-github/
> README: update OE core and meta-openembedded URIs

- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
Drop board-2.bin file, board data has been merged into linux-firmware.
> firmware-qcom-dragonboard845c: drop WiFi board-2.bin file

- conf/machine/sa8155p-adp.conf
Add support for building qcs8155p-adp dtb.
Basically both the sa8155p-adp and qcs8155p-adp boards
use the same adp motherboard but have different
SoC daughter cards mounted on the adp motherboard
respectively.
> conf/sa8155p-adp.conf: Add support for building qcs8155p-adp dtb

- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard820c.bb
Add dependencies on APQ8096's aDSP and modem firmware.
> packagegroup-firmware-dragonboard820c: add missing dependencies

- conf/machine/include/qcom-common.inc
With the removal of xf86-input-keyboard recipe form oe-core, meta-qcom
now depends on the unavailable package. While we are at it, follow the
change applied in 2016 to oe-core and also drop xf86-input-mouse.
xf86-input-evdev and -libinput should handle everything instead.
Note: the oe-core has also dropped the -evdev driver, but I'd prefer to
be safe than sorry and leave it in place for now.
> qcom-common.inc: drop legacy/obsolete xf86-input drivers

- conf/machine/qcom-armv7a.conf
The dtb name for Castor has been changed upstream. Drop it for now,
to allow building all kernel versions.
> qcom-armv7a: disable Sony Xperia Castor dtb

- recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
The override in the bbappend is Qualcomm-specific, it should not be
applied to other platforms, thus add the :qcom: override to prevent it
from being applied to other platforms.
> pulseaudio: guard the qcom-specific workaround with 'qcom' override

- recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
Fixes e5a2eb2f4409 (pulseaudio: guard the qcom-specific workaround
with 'qcom' override).
The order of the overrides was incorrect resulting in build failures.
Reported-by: Leonardo Sandoval <leonardo.sandoval@linaro.org>
> pulseaudio: fix use of overrides

- recipes-test/images/initramfs-test-image.bb
This adds mybw to the initramfs-test-image install list.
Signed-off-by: Neil Armstrong <neil.armstrong@linaro.org>
> recipes-test: initramfs-test-image: install mybw

- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-adbd-cmdline.bb
- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-adbd-cmdline/50-adbd-cmdline.conf
- recipes-test/images/initramfs-test-image.bb
Install and enable adbd if meta-openmebedded is enabled.
> initramfs-test-image: add adbd support

- recipes-bsp/firmware/firmware-wcn6855_git.bb
- recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Firmware from linux-firmware has issues on sm8450/wcn6856 platforms
(inability to load board file). Allow installing alternative firmware
files.
> Fix alternative wcn6855 firmware packaging

- conf/machine/qcom-armv8a.conf
It is convenient to be able to override the boot image parameters, in local.conf during development, so let's use ?= operator where it was not used.
> machine: qcom-armv8a: make sure defaults vars can be overriden

- recipes-kernel/linux/linux-qcom-bootimg.inc
Currently linux-qcom-bootimg.inc issues warnings like the following with some versions of Python 3:
```
WARNING: linux-linaro-qcomlt-6.0-r0 do_qcom_img_deploy: .../meta-qcom/recipes-kernel/linux/linux-qcom-bootimg.inc:51: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
Using `is` to test for equality is wrong. `is` only works "by accident" and relies on some rather dubious assumptions about how CPython manages the string literal pool
There are three occurrences, the first two are fixed the obvious way and the final one is simply removed because the code was unreachable anyway (the empty string already evaluates to False when used in a logic expression).
Signed-off-by: Daniel Thompson <daniel.thompson@linaro.org>
> linux-qcom-bootimg: Fix SyntaxWarning messages

- recipes-devtools/debugcc/debugcc/0001-msm8996-add-block-names.patch
- recipes-devtools/debugcc/debugcc/block/0001-debugcc-add-support-for-printing-clocks-from-a-singl.patch
- recipes-devtools/debugcc/debugcc/block/0002-debugcc-add-block-names-to-all-platforms.patch
- recipes-devtools/debugcc/debugcc/msm8996/0001-debugcc-preserve-xo_div4-contents.patch
- recipes-devtools/debugcc/debugcc/msm8996/0002-msm8996-add-support-for-MSM8996-platform.patch
- recipes-devtools/debugcc/debugcc/msm8996/0003-debugcc-allow-customizing-the-measurement-process.patch
- recipes-devtools/debugcc/debugcc/msm8996/0004-msm8996-add-support-for-CPU-clocks.patch
- recipes-devtools/debugcc/debugcc_git.bb
Bring in patches that I use on a daily bases:
- msm8996 support
- filtering of the clock controllers
Corresponding PRs: https://github.com/andersson/debugcc/pull/10, https://github.com/andersson/debugcc/pull/8
> Debugcc updates

- recipes-test/images/initramfs-test-image.bb
Enable tools which can be used to test v4l devices on Qualcomm boards. This causes image growth of 419 KiB.
> initramfs-test-image: enable media-ctl and yavta tools

- recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
Since 7f2430cda819 (ASoC: qcom: q6asm-dai: Add SNDRV_PCM_INFO_BATCH flag), in the mainline kernel, we no longer need to explicitely disable the timer based scheduling in PA, since the driver correctly reports SNDRV_PCM_INFO_BATCH.
> pulseaudio: remove tsched=0 workaround

- recipes-graphics/mesa/mesa_%.bbappend
Mesa can provide several tools which simplify debugging mesa and the kernel driver. Enable them to be built into the mesa-tools package.
> mesa: enable tools package

- recipes-graphics/mesa/mesa_git.bb
- recipes-kernel/linux/linux-linaro-qcomlt-dev.bb
Fix two errors caused by `AUTOREV` usage:
> ERROR: /home/lumag/Projects/RPB/build-rpb/conf/../../layers/meta-qcom/recipes-graphics/mesa/mesa_git.bb: AUTOREV/SRCPV set too late for the fetcher to work properly, please set the variables earlier in parsing. Erroring instead of later obtuse build failures.
ERROR: /home/lumag/Projects/RPB/build-rpb/conf/../../layers/meta-qcom/recipes-kernel/linux/linux-linaro-qcomlt-dev.bb: AUTOREV/SRCPV set too late for the fetcher to work properly, please set the variables earlier in parsing. Erroring instead of later obtuse build failures.
> Fix AUTOREV parsing

- recipes-devtools/skales/skales_git.bb
Skales is still pulling from the now defunct (RIP) codeaurora. Update to point it to codelinaro.
> skales: switch git url to codelinaro

- README.md
- Fix the URL to point to github.com/Linaro/meta-qcom
- Change the maintainer of meta-qcom to me
- Remove the mailing list option to submit patches
> README.md: meta-qcom takeover

- recipes-bsp/firmware-nexus/firmware-qcom-nexus.inc
- recipes-bsp/firmware-nexus/firmware-qcom-pixel.inc
- recipes-bsp/firmware-nexus/firmware-qcom-radio.inc
Rework the recipe dependecies to work with the recent bitbake/OE changes. Provide explicit dependencies for the do_extract task so that the syroot is fully staged and populated, otherwise some of the tools might be missing from the native sysroot at the do_extract time.
> firmware-nexus: fix firmware-nexus* dependencies

- recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
Remote the xshmfence PACKAGECONFIG, removed in oe-core while converting the recipe from autotools to meson.
> xserver-xorg: drop the xshmfence PACKAGECONFIG

- recipes-kernel/linux/linux-linaro-qcomlt_6.0.bb
Bump SRCREV to include a fix for 32-bit machines and gcc-13.
> linux-linaro-qcomlt_6.0: bump SRCREV

- conf/machine/qcom-armv7a.conf
Follow the lead of qcom-armv8a and add a unified machine config to be used for all devices using late (S4 and early 400/600/800 series) 32-bit Qualcomm Snapdragon based devices.
Do not use this machine for SDXnn modems or for Snapdragon S1/S2/S3.
> qcom-armv7a: add unified machine for 32-bit Snapdragon devices

- recipes-bsp/firmware/firmware-qcom-dragonboard410c.inc
The rmtfs service will default to using partitions instead of file images. Stop shipping /boot/modem_fsg and demand fsg partition to be flashed properly (via the rescue package).
> firmware-qcom-dragonboard410c: stop shipping /boot/modem_fsg

- recipes-bsp/firmware/firmware-qcom-dragonboard-apq8074.bb
- recipes-bsp/firmware/firmware-qcom-ifc6410.bb
- recipes-bsp/firmware/firmware-qcom-ifc6560.bb
- recipes-bsp/firmware/firmware-qcom-nhlos.inc
- recipes-bsp/firmware/firmware-qcom-sm8350-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard-apq8074.bb
- recipes-bsp/packagegroups/packagegroup-firmware-ifc6410.bb
- recipes-bsp/packagegroups/packagegroup-firmware-ifc6560.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8350-hdk.bb
Sometimes it's necessary to build the image using firmware files from vendor-provided `NON-HLOS.bin`, `proprietary.tar.gz` or `adreno.tar.gz` (e.g. see #366 ). Add include files and example recipes to build firmware for ifc6410 and ifc6560 boards.
> Add support for packaging firmware from proprietary archives 

- recipes-bsp/firmware/firmware-qcom-dragonboard410c.inc
As the corresponding firmware files have been merged to the linux-firmware archive and recipe, stop shipping actual firmware files. Provide just compatibility links for the historical kernel.
> firmware-qcom-dragonboard410c: stop shipping firmware files

- recipes-bsp/packagegroups/packagegroup-firmware-rb1.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb2.bb
- recipes-kernel/linux/linux-linaro-qcomlt_6.4.bb
- Include lt9611uxc firmware into corresponding packagesgroups
- Bump 6.4 SRCREV to fix interconnects support on RB2 board (and also to bring GPU to the RB2 board).
> Update RB1/RB2 support

- recipes-bsp/firmware/firmware-qcom-rb1_20230724-v1.bb
- recipes-bsp/firmware/firmware-qcom-rb2_20230724-v1.bb
- recipes-bsp/firmware/firmware-qcom.inc
- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard820c.bb
- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard845c.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb1.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb2.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb5.bb
In OE-core the Adreno packages were split into platform-dependent and platform-independent parts. Sync with these changes.
> Fix Adreno ZAP shader packaging

- recipes-kernel/linux/linux-linaro-qcom.inc
- recipes-support/fastrpc/fastrpc_git.bb
Linaro git trees have been moved from git.linaro.org to git.codelinaro.org.
(cherry picked from commit f6124d7878154c7f1307d3ed0abca5bdc17d3e1f)
> kernel: switch git url to codelinaro

- recipes-support/qbootctl/files/0001-Fix-to-uint32_t-has-not-been-declared.patch
- recipes-support/qbootctl/files/qbootclt-bless-boot.service.in
- recipes-support/qbootctl/qbootctl_0.1.2.bb
Add qbootclt package to control the boot A/B slot flags.
> Add qbootctl package

- README.md
README.md needed update to reflect the move of #linaro IRC channel from Freenode to Libera Chat
> Subject of Change: Changed Freenode IRC to Libera Chat

- .github/workflows/daily.yml
- .github/workflows/premerge.yml
- .github/workflows/push.yml
Stop testing images for the legacy machines. The qcom-armv8a is used instead.
> CI: drop legacy machines support

- recipes-support/pd-mapper/pd-mapper_git.bb
https://github.com/andersson/pd-mapper moved ahead and has critical fixes for pd-mapper functionality. Updated the corresponding recipe (recipes-support/pd-mapper/pd-mapper_git.bb) to catch up these changes.
> recipes-support: pd-mapper bump to rev 10997ba

- .github/workflows/daily.yml
The kirkstone branch wasn't migrated to qcom-armv7a-modem machine. Continue using sdx55-mtp for the CI on that branch.
> CI: use sdx55-mtp for kirkstone

- conf/machine/include/qcom-common.inc
As we are transitioning to linux-yocto, make the life of machine config files easier and let qcom-common.inc be less insisting on the preferred kernel recipe.
> qcom-common.inc: make it less insisting on the default kernel

- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
Change the conditional argument to check if androidserial is non-empty.
Initially we observed the following logs on boot-up as well as on running `systemctl restart android-tools-adbd`
Boot-up logs:
```txt
Apr 28 17:42:28 qcm6490 systemd[1]: Starting Android Debug Bridge...
Apr 28 17:42:28 qcm6490 systemd[1]: android-tools-adbd.service: Control process exited, code=exited, status=1/FAILURE
Apr 28 17:42:28 qcm6490 android-gadget-cleanup[518]: /usr/bin/android-gadget-cleanup: cd: line 7: can't cd to adb: No such file or directory
Apr 28 17:42:28 qcm6490 android-gadget-cleanup[518]: /usr/bin/android-gadget-cleanup: line 9: can't create UDC: Permission denied
Apr 28 17:42:28 qcm6490 android-gadget-cleanup[520]: killall: adbd: no process killed
Apr 28 17:42:28 qcm6490 …
```
> android-gadget-setup: fix conditional argument to assign serial variable

- conf/machine/qcom-armv8a.conf
Fix the warnings introduced by qcm6490-rb3g2 support:
WARNING: KERNEL_DEVICETREE:append:pn-linux-yocto += is not a recommended operator combination, please replace it. WARNING: KERNEL_DEVICETREE:append:pn-linux-yocto += is not a recommended operator combination, please replace it.
There is no need to use += together with the append.
> qcom-armv8a: fix the freshly introduced warnings

- recipes-bsp/firmware/firmware-qcom-adreno.inc
- recipes-bsp/firmware/firmware-qcom-ifc6560.bb
- recipes-bsp/firmware/firmware-qcom-sm8150-hdk.bb
- recipes-bsp/firmware/firmware-qcom-sm8350-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-ifc6560.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8150-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8350-hdk.bb
Process archives with Adreno firmware (e.g. proprietary.tar.gz) to extract Adreno zap shaders (and GMU for sm8150).
> Add Adreno firmware to the packaged firmware for several boards

- classes/linux-qcom-bootimg.bbclass
- classes/uki.bbclass
- conf/machine/include/qcom-common.inc
- recipes-core/systemd/systemd-boot-native_254.4.bb
- recipes-kernel/images/esp-qcom-image.bb
- recipes-kernel/linux/linux-linaro-qcom.inc
- recipes-kernel/linux/linux-yocto_%.bbappend
To support systemd-boot as a boot manager, need to create an esp.bin with uki, uefi stub and other essential packaged into it. 
This is achieved in below patches.
1. Extend systemd-boot recipe through a bbappend to provide Ukify tool.
2. Add linux-qcom-efiimg bbclass to generate uki and in turn pack this uki into esp.bin
3. Inherit linux-qcom-efiimg bbclass in linux-yocto & linux-linaro recipes to generate esp.bin
> Efi boot support

- recipes-graphics/mesa/mesa_%.bbappend
The XA tracker is only useful for the VMWare DDX driver. Drop it from PACKAGECONFIG_FREEDRENO. (xa tracker has been used for the xf86-video-freedreno driver, but it has been repalced by the generic modeswitching driver).
> mesa: stop requiring the XA tracker

- recipes-bsp/firmware/firmware-qcom-sm8150-hdk.bb
Current recipes ends up installing a640_gmu.bin to FW_QCOM_PATH /lib/firmware/qcom/sm8150, while it should be installed to FW_QCOM_BASE_PATH (/lib/firmware/qcom/). Insall it manually to fix the installation path.
> firmware-qcom-sm8150-hdk: fix GMU binary installation

- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-adbd-cmdline.bb
- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-adbd-cmdline/50-adbd-cmdline.conf
- recipes-test/images/initramfs-test-image.bb
This is a rebased copy of #397 to kirkstone branch
---
 
Install and enable adbd if meta-openmebedded is enabled.
> kirkstone: initramfs-test-image: add adbd support

- recipes-kernel/linux/linux-yocto/qcm6490-dtsi/0001-PENDING-arm64-dts-qcom-qcm6490-disable-qcom-watchdog.patch
- recipes-kernel/linux/linux-yocto_6.6.bbappend
Disable qcom watchdog for qcm6490 boards. With hypervisor enabled on qcm6490, accessing watchdog registers results into an external abort.
> linux-yocto: disable qcom watchdog for QCM6490

- .github/workflows/build-template.yml
Update CI to use actions/setup-python@v5 action to fix the GitHub warning.
> CI: update to actions/setup-python@v5

- recipes-kernel/linux/linux-linaro-qcomlt_6.0.bb
Bump the 6.0 kernel revision to fix missing configuration items (and also to bring some of bugfixes).
> linux-linaro-qcomlt: bump 6.0 kernel

- recipes-kernel/linux/linux-linaro-qcomlt_6.6.bb
- recipes-kernel/linux/linux-yocto/bsp/qcom-armv7a/qcom-armv7a-standard.scc
- recipes-kernel/linux/linux-yocto/bsp/qcom-armv8a/qcom-armv8a-standard.scc
Enable the fuse feature, used by the RPB images.
> linux-yocto: enable fuse to unbreak RPB images.

- recipes-kernel/linux/linux-linaro-qcomlt_6.6.bb
- recipes-kernel/linux/linux-yocto/0001-ASoC-codecs-wsa881x-set-clk_stop_mode1-flag.patch
- recipes-kernel/linux/linux-yocto_6.6.bbappend
Backport patch fixing playback issues on the RB5 board, which uses WSA881x codec.
> Fix playback using WSA881x codecs

- recipes-kernel/linux/linux-linaro-qcomlt_6.0.bb
Bump SRCREV to include a patch for the WSA881x codec.
> linux-linaro-qcomlt: bump SRCREV

- recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-UPSTREAM-arm64-dts-qcom-qcs6490-rb3gen2-Enable-adsp-.patch
- recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0001-UPSTREAM-arm64-dts-qcom-sc7280-move-MPSS-and-WPSS-me.patch
- recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-UPSTREAM-arm64-dts-qcom-qcs6490-rb3gen2-Enable-vario.patch
- recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-UPSTREAM-arm64-dts-qcom-sc7280-Add-ADSP-node.patch
- recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0003-UPSTREAM-arm64-dts-qcom-qcm6490-idp-Enable-various-r.patch
- recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0003-UPSTREAM-arm64-dts-qcom-sc7280-Add-CDSP-node.patch
- recipes-kernel/linux/linux-yocto/qcm6490-drivers/0001-UPSTREAM-remoteproc-qcom_q6v5_pas-Add-SC7280-ADSP-CD.patch
- recipes-kernel/linux/linux-yocto/qcm6490-dtsi/0001-UPSTREAM-dt-bindings-remoteproc-qcom-sc7180-pas-Fix-.patch
- recipes-kernel/linux/linux-yocto/qcm6490-dtsi/0002-UPSTREAM-dt-bindings-remoteproc-qcom-sc7180-pas-Add-.patch
- recipes-kernel/linux/linux-yocto/qcm6490-dtsi/0003-UPSTREAM-arm64-dts-qcom-sc7280-Use-WPSS-PAS-instead-.patch
- recipes-kernel/linux/linux-yocto/qcm6490-dtsi/0004-UPSTREAM-arm64-dts-qcom-sc7280-Remove-unused-second-.patch
- recipes-kernel/linux/linux-yocto/qcm6490-dtsi/0005-UPSTREAM-arm64-dts-qcom-sc7280-Rename-reserved-memor.patch
- recipes-kernel/linux/linux-yocto_6.6.bbappend
Add support for the ADSP, CDSP and WPSS remoteprocs found on SC7280 and enable various applicable remoteproc nodes for qcm6490-idp and qcs6490-rb3gen2.
This has dependency on PR#587.
> linux-yocto: enable various remotprocs for qcm6490 boards

- recipes-bsp/firmware-woa/firmware-qcom-ecs-liva-qc710_200.0.10.0.bb
- recipes-bsp/images/initramfs-firmware-ecs-liva-qc710-image.bb
- recipes-bsp/packagegroups/packagegroup-firmware-ecs-liva-qc710.bb
ECS Liva QC710 is a devkit for SC7180 platform. Package firmware for the device.
> Package firmware for ECS Liva QC710

- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-adbd-cmdline.bb
This reverts commit 53e55107662c788e2aba77d8bafc5d242d725772.
> Revert "android-tools-adbd-cmdline: Use UNPACKDIR instead of WORKDIR"

- recipes-test/bootrr/bootrr_git.bb
In order to fix bootrr on db410c, bump bootrr to the latest revision. While we are at it, point the recipe to the new repo location.
> bootrr: bump to the latest revision

- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-adbd-cmdline/50-adbd-cmdline.conf
If android-tools-adbd.service service needs to be up upon boot, then the path assigned to ConditionPathExists must be present at boot time. This means that the path set to ConditionPathExists must be created at build time itself. /etc is a better place to keep files and directories that are created at build time rather than /var. /var is expected to house files that are created at run time.
Hence, change ConditionPathExists=|/var/usb-debugging-enabled to ConditionPathExists=|/etc/usb-debugging-enabled in 50-adbd-cmdline.conf file.
> 50-adbd-cmdline.conf: Change /var to /etc in ConditionPathExists

- conf/machine/qcom-armv8a.conf
- recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
- recipes-bsp/images/initramfs-firmware-image.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
- recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Add firmware package support for QCS6490 RB3Gen2 board.
This PR addresses the same purpose as the existing PR #551. However, due to limitations in writing to @kraparthy’s tree, we created this fresh PR. Please note that @kraparthy is no longer part of this project.
> Add firmware package support for QCS6490 RB3Gen2

- recipes-kernel/linux/linux-yocto/qrb4210-dts/0002-arm64-dts-qcom-qrb4210-rb2-Enable-bluetooth.patch
Make RB2 BlueTooth patch applicable again after the stable kernel bump.
> linux-yocto: fix RB2 BlueTooth patch

- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/ath11k-generate-board-2_json.sh
ath11k tools have slighly changed the format of the board-2.json by adding a nested board / regdb arrays. Fix the script that generates board-2.json to accomodate for those changes.
> qca-swiss-army-knife: fix ath11k/board-2.json generation

- conf/machine/include/qcom-common.inc
Now as the OE-Core has gained several linux-yocto versions, specify the preferred one.
> qcom-common.inc: set PREFERRED_VERSION for linux-yocto

- recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb5.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8350-hdk.bb
Follow the OE-Core changes and use linux-firmware-qcom-vpu package instead of the (removed) l-l-qcom-vpu-1.0 and l-f-qcom-vpu-2.0.
> packagegroups-firmware-*: use linux-firmware-qcom-vpu

- conf/machine/include/qcom-common.inc
- recipes-kernel/images/esp-qcom-image.bb
- recipes-kernel/images/linux-qcom-uki.bb
If a DTB is present in UKI, systemd-boot can override the default UEFI provided DTB. This provisioning of DTB via UKI allows the users to customize DTBs as per product needs without regenerating the firmware.
> Support optional dtb loading via UKI

- classes/linux-qcom-dtbbin.bbclass
- recipes-kernel/linux/linux-yocto_%.bbappend
This PR introduces a bbclass, which upon inherited by kernel will produce a vfat image for each device-tree blob generated by kernel.
This helps to meet one of the ARM System Ready IR requirements of keeping dtb out of kernel binary.
> Generate vfat image by packing device-tree blob.

- recipes-test/images/initramfs-test-full-image.bb
Invert the condition so that crash gets disabled for musl systems.
> initramfs-test-full-image: fix the musl condition

- .github/workflows/build-template.yml
This reverts commits 3a3204a ("CI: also enable meta-python") and
d208627 ("CI: temporarily add meta-oe to the setup"). Enabling
meta-oe and meta-python results in a lot of issues. Build dependencies
of esp-qcom-image will be handled in a different way
> CI: revert meta-oe/meta-python enablement 

- conf/machine/qcom-armv8a.conf
Hi,
Testing rb3gen2 build some build errors have been found.
Let's fix that by this patchset.
Regards,
Tommaso
> meta-qcom: build fixes

- .github/workflows/build-template.yml
Enable building of the images with and without initramfs so that all possible dependencies between the kernel and the initramfs are covered.
> CI: Enable building of the images with and without initramfs

- recipes-vendor-in/python/python3-pefile/run-ptest
- recipes-vendor-in/python/python3-pefile_2024.8.26.bb
Vendor the recipe from meta-oe. This allows us to build the esp-qcom-image without adding dependency on the meta-oe. Python-pefile should be moved from meta-oe to OE-Core, then this recipe can be dropped.
Suggestd-by: Ricardo Salveti <ricardo@foundries.io>
> python3-pefile: vendor in the recipe

- .github/workflows/build-template.yml
The kernel.bbclass already contains default assignment, drop the manual assignment of the INITRAMFS_IMAGE variable to the empty string in the CI setup.
> CI: drop initramfs assignment in -noinitramfs case

- recipes-kernel/images/linux-qcom-uki.bb
Fixed below error in linux-qcom-uki.bb when INITRAMFS_IMAGE is undefined.
ERROR: Error for linux-qcom-uki.bb:do_configure[depends], dependency '${@ '${INITRAMFS_IMAGE}:do_image_complete' if d.getVar('INITRAMFS_IMAGE') else ''}' does not contain exactly one ':' character. Task 'depends' should be specified in the form 'packagename:task'
> Fix build error if INITRAMFS_IMAGE undefined

- recipes-kernel/images/linux-qcom-uki.bb
Below error seen when INITRAMFS_IMAGE is undefined. Fix it by defining INITRAMFS_IMAGE with a weak assignment.
ERROR: Error for linux-qcom-uki.bb:do_configure[depends], dependency '${@ '${INITRAMFS_IMAGE}:do_image_complete' if d.getVar('INITRAMFS_IMAGE') else ''}' does not contain exactly one ':' character. Task 'depends' should be specified in the form 'packagename:task'
Signed-off-by: Viswanath Kraleti <quic_vkraleti@quicinc.com>
(cherry picked from commit 2de73afc76249027916accd9a83a6e66fa85a4dd)
> linux-qcom-uki.bb: Initialize INITRAMFS_IMAGE to stop breaking builds

- conf/machine/qcom-armv8a.conf
- recipes-bsp/u-boot/u-boot-qcom-common_2024.10.inc
- recipes-bsp/u-boot/u-boot-qcom_git.bb
- recipes-devtools/qtestsign/qtestsign_git.bb
Hi,
This patchset add the initial support for u-boot-qcom.
This has been tested on rb3gen2 board:
Flashing the image using fastboot:
```
fastboot flash uefi_a ./u-boot-qcs6490-rb3gen2.mbn
```
Below some logs from the test.
```
U-Boot 2024.10-rc4-00620-ga61af132fb90 (Sep 09 2024 - 10:00:06 +0000)
Model: Qualcomm Technologies, Inc. Robotics RB3gen2
DRAM:  6 GiB (effective 5.9 GiB)
serial_msm_geni serial@994000: pinctrl_select_state_full: uclass_get_device_by_phandle_id: err=-19
serial_msm_geni serial@994000: pinctrl_select_state_full: uclass_get_device_by_phandle_id: err=-19
Core:  57 devices, 28 uclasses, devicetree: board
Loading Environment from nowhere... OK
In:    serial,button-kbd
Out:   serial,vidconsole
Err:   serial,vidconsole
qcom-ufshcd ufs@1d84000: Qcom UFS HC version: 4.3.0 …
```
> meta-qcom: initial u-boot support

- .github/workflows/build-template.yml
- .github/workflows/daily.yml
- .github/workflows/premerge.yml
- .github/workflows/push.yml
There is little point in retaining full set of build artifacts for the test builds, which is what the empty "artifacts" config does. Keep just the licences and throw away everything else.
> CI: retain only licenses as build artifacts

- conf/machine/include/qcom-common.inc
- conf/machine/qcom-armv8a.conf
Listing 'Image' multiple times in KERNEL_IMAGETYPES list leads to fatal QA errors while packaging [packages-list]. Using += operator instead of :append to add to list helps to avoid duplication.
> Don't list 'Image' multiple times in KERNEL_IMAGETYPES

- recipes-kernel/images/linux-qcom-uki.bb
In response to https://github.com/quic-yocto/meta-qcom-hwe/pull/42.
KERNEL_IMAGETYPES is not enough to be checked, since kernel types can also be set using KERNEL_IMAGETYPE or KERNEL_ALT_IMAGETYPE. Like it's done in OE-core kernel class, we need to combine all these variables.
> linux-qcom-uki: KERNEL_IMAGETYPES should be fully populated before use

- recipes-kernel/images/linux-qcom-uki.bb
Move the kernel Image check to the same python parsing logic created for merging KERNEL_IMAGETYPES, as SKIP_RECIPE does not take into account dynamic python logic, rejecting the updated KERNEL_IMAGETYPES value.
Since KERNEL_IMAGETYPES is not used anywhere else in the recipe, remove setVar and just use the merged 'types' variable instead.
> linux-qcom-uki: use bb.parse.SkipRecipe for the kernel Image check

- dynamic-layers/openembedded-layer/recipes-bsp/packagegroups/packagegroup-firmware-ecs-liva-qc710.bb
- dynamic-layers/openembedded-layer/recipes-bsp/packagegroups/packagegroup-firmware-lenovo-miix-630.bb
- dynamic-layers/openembedded-layer/recipes-bsp/packagegroups/packagegroup-firmware-lenovo-yoga-c630.bb
- dynamic-layers/openembedded-layer/recipes-bsp/packagegroups/packagegroup-firmware-sc8180x.bb
- recipes-bsp/images/initramfs-firmware-ifc6560-image.bb
- recipes-bsp/images/initramfs-firmware-pixel3-image.bb
- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard845c.bb
- recipes-bsp/packagegroups/packagegroup-firmware-ifc6560.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb1.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb2.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8150-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8650-hdk.bb
Now as there is a separate package providing just WCN3990 data, stop
pulling the big ath10k firmware package and install just the required
data.
> switch to linux-firmware-ath10k-wcn3990

- .github/workflows/premerge.yml
- .github/workflows/push.yml
In order to be more flexible, manually specify build variants (machine-libc-kernel-subtype)
(cherry picked from commit 3c5a909a702a4ac0f97497e2e7ff33b22787e6bd)
> CI: manually specify build matrix

- recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
Stop providing the DSP and Adreno firmware as a part of the firmware-qcom-rb3gen2 recipe, they are now a provided by the linux-firmware recipe.
> firmware-qcom-rb3gen2: migrate to linux-firmware

- dynamic-layers/openembedded-layer/recipes-bsp/firmware-woa/firmware-qcom-x1e80100_200.0.32.0.bb
Audio firmware for X1E80100 devices is now being provided by the linux-firmware package, drop it from the WoA firmware package.
> firmware-qcom-x1e80100: drop audio firmware

- recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-UPSTREAM-dt-bindings-arm-qcom-Add-QCM6490-IDP-and-QC.patch
The Signed-off-by tag in this kernel patch is bogus, as reported by the Yocto patchreview script:
Malformed Signed-off-by 'Signed-off by:' (<meta-qcom-new>/recipes-kernel/linux/linux-yocto/qcm6490-board-dts/0002-UPSTREAM-dt-bindings-arm-qcom-Add-QCM6490-IDP-and-QC.patch)
> linux-yocto: fix Signed-off-by tag

- recipes-bsp/firmware/firmware-qcom-rb3gen2_00039.2.bb
It should be a dependency on the -native flavor, since the tool is used during the build. Interestingly it worked fine so far! That's because pil-squasher-native is already added to DEPENDS in firmware-qcom-adreno.inc.
I have decided to leave it here as well, since pil-squasher is used in this recipe too.
With pil-squasher in DEPENDS, it breaks the yocto-checklayer script with:
allarch firmware-qcom-rb3gen2:do_prepare_recipe_sysroot: a4777557300156768d6ed9c776ef216d82576f103a9382c35ac6595e3008c967 (qcm6490-idp, sa8775p-ride-sx, qcs6490-rb3gen2-core-kit) != a121b24b301e93b1153c72e858cf4ced5217306d9a7c9ed51bf14c56434c1ce3 (qcom-armv7a) != 16bcafbe404dd2e0b58c4a86ca923c8760273fac69a8237008f78f3d4f9b2efe (qcom-armv7a-modem) != a5cfc0b555ce8fc4b76bfdd5a1f9c600cb9db2ac052005d43109ebe239fbd902 …
> firmware-qcom-rb3gen2: fix dependency on pil-squasher

- recipes-devtools/qdl/qdl_git.bb
Update to the latest commit of the upstream repository https://github.com/linux-msm/qdl.git.
Relevant changes from latest upstream:
- support for old libusb
- support for building across ubuntu variants
- updates to firehose configuration
- support for <read> operations
> qdl: update to the latest upstream

- README.md
Improved the markdown syntax in README for links and code blocks. Further, fixed the syntax of hyperlink for Yocto Project Quick Build.
> README: markdown syntax fix for links

- recipes-devtools/qdl/qdl_git.bb
Update to the latest commit of the upstream repository: https://github.com/linux-msm/qdl.git.
Relevant changes from latest upstream:
- support for old libusb
- support for building across ubuntu variants
- updates to firehose configuration
- support for `<read>` operations
> scarthgap: qdl: update to the latest upstream

- recipes-devtools/qdl/qdl_git.bb
Update to the latest commit of the upstream repository: https://github.com/linux-msm/qdl.git.
Relevant changes from latest upstream:
- support for old libusb
- support for building across ubuntu variants
- updates to firehose configuration
- support for `<read>` operations
> kirkstone: qdl: update to the latest upstream

- .github/workflows/build-template.yml
- .github/workflows/premerge.yml
- .github/workflows/push.yml
In preparation of the master branch switching to 'kas' (as a part of the ownership transfer), switch the branch to use a local copy of build-template.yml
> CI: copy build-template from master branch

- recipes-bsp/firmware/firmware-qcom-dragonboard-apq8060.bb
- recipes-bsp/firmware/firmware-qcom-nhlos.inc
Add recipe for packaging firmware for Dragonboard APQ8060, the oldest Qualcomm board supported by the Linux kernel.
> Firmware for Dragonboard APQ8060

- .github/workflows/test.yml
foundriesio/lava-action@v5 fixes a typo in input variable handling. It also fixes a potential security vulnerability in undici library.
> workflows: upgrade lava-action to v5

- .github/workflows/build-yocto.yml
- classes-recipe/image_types_qcom.bbclass
Create image-specific subfolder in DEPLOY_DIR_IMAGE besides qcomflash tarball archive. This allows to run QDL for device flashing on that folder directly for local builds.
> image_types_qcom: create image-specific subfolders

- README.md
Drop the unpack archive step, as since 8f9de8a8('image_types_qcom: create image-specific subfolders'), image-specific subdirectories have been created along with ready-to-flash artifacts, making the tarball unpack step unnecessary.
> README: drop tarball unpack step

- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs6490_00058.0.bb
- recipes-bsp/partition/qcom-partition-confs/qcm6490-partitions.conf
PR to bring the latest partition conf and boot firmware from qclinux 1.3.
Relevant boot firmware changes:
- KVM support via xbl_config_kvm.elf
- UEFI variable runtime support (read-only since write requires RPMB)
- UEFI Capsule Update via capsule as file
As with qclinux 1.3, it requires UFS reprovisioning as described at https://docs.qualcomm.com/bundle/publicresource/topics/80-70017-253/set_up_the_device.html?vproduct=1601111740013072&version=1.3#ubuntu-machine
> Update rb3gen2 partition conf and boot firmware with the qclinux 1.3 release

- .github/workflows/build-yocto.yml
- ci/qcs9100-ride-sx.yml
- conf/machine/qcs9100-ride-sx.conf
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00006.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00058.0.bb
- recipes-bsp/partition/qcom-partition-confs/qcs9100-partitions.conf
- recipes-bsp/partition/qcom-partition-confs_1.0.bb
Aligning the machine name with qclinux 1.2/1.3, which is now qcs9100-ride-sx (essentially the same, new naming) and bringing the latest partition configuration and boot firmware.
With these changes I'm able to boot my sa8775p/qcs9100-ride-sx with mainline.
> Fix support for QCS9100/SA8775p-ride-sx

- recipes-test/images/initramfs-test-image.bb
The v4l-utils package contains a set of utils useful to test and debug V4L2 devices, CEC devices and (in the next release branch) will get the edid-decode binary. Add the v4l-utils package to the list of packages included into the initramfs-test-image.
Drawback: the image grows by about 850 KBytes.
> initramfs-test-image: add v4l-utils package

- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard845c.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb5.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8150-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8350-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8450-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8550-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8650-hdk.bb
OE-Core has split single `linux-firmware-qca` package into smaller packages. Follow the split and select only required firmware packages for the Qualcomm boards.
> Follow QCA firmware packages split

- classes/linux-qcom-dtbbin.bbclass
- conf/machine/include/qcom-common.inc
- recipes-kernel/images/esp-qcom-image.bb
Set default vfat sector size for UFS devices and partitions.
> Fix default vfat sector size for the UFS devices and partitions

- ci/base.yml
- ci/distro.yml
- ci/yocto-check-layer.sh
- ci/yocto-patchreview.sh
Consume the upstream repos directly, not through the combo repo.
> CI: rework to enable optional meta-qcom-distro configs

- recipes-bsp/packagegroups/packagegroup-firmware-rb1.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb2.bb
Make firmware packagegroups for RB1 and RB2 boards select necessary Bluetooth firmware.
> Pick up Bluetooth firmware for RB1 and RB2 boards

- recipes-bsp/packagegroups/packagegroup-firmware-rb1.bb
Correct c&p error, RB1 (qrb2210) has the Adreno 702, which uses linux-firmware-qcom-adreno-a702 instead of -a630. Select the correct firmware package.
> packagegroup-firmware-rb1: select A702 firmware package

- recipes-bsp/packagegroups/packagegroup-firmware-dragonboard820c.bb
Follow the qca firmware package split and RRECOMMEND only the linux-firmware-qca-qca61x4-serial package.
> packagegroup-firmware-dragonboard-820c: use split qca fw package

- recipes-bsp/firmware/firmware-ath6kl_git.bb
- recipes-bsp/u-boot/u-boot-qcom_git.bb
- recipes-devtools/debugcc/debugcc_git.bb
- recipes-devtools/partition-utils/qcom-ptool_git.bb
- recipes-devtools/pil-squasher/pil-squasher_git.bb
- recipes-devtools/qc-image-unpacker/qc-image-unpacker_git.bb
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife_git.bb
- recipes-devtools/qmic/qmic_git.bb
- recipes-devtools/skales/skales_git.bb
- recipes-support/fastrpc/fastrpc_git.bb
- recipes-support/pd-mapper/pd-mapper_git.bb
- recipes-support/qrtr/qrtr_git.bb
- recipes-support/rmtfs/rmtfs_git.bb
- recipes-support/tqftpserv/tqftpserv_git.bb
- recipes-test/bootrr/bootrr_git.bb
- recipes-test/diag/diag_git.bb
- recipes-test/mybw/mybw_git.bb
Drop SRCPV similarly like oe-core did in 2023. The SRCPV is now handled as a part of PKGV handling:
https://git.openembedded.org/openembedded-core/commit/?h=nanbield&id=843f82a246a535c353e08072f252d1dc78217872
> recipes: drop ${SRCPV}

- recipes-bsp/packagegroups/packagegroup-firmware-rb3gen2.bb
Add Adreno Zap shader to the list of RB3 Gen2 firmware packages.
> packagegroup-firmware-rb3gen2: add Adreno ZAP binary

- conf/machine/include/qcom-common.inc
- conf/machine/qcm6490-idp.conf
- conf/machine/qcom-armv7a.conf
- conf/machine/qcom-armv8a.conf
- conf/machine/qcs6490-rb3gen2-core-kit.conf
- conf/machine/qcs9100-ride-sx.conf
Pulled out from #756, this PR puts all common `MACHINE_FEATURES` in qcom-common.inc and adds `pci` to RB3.
> Rework MACHINE_FEATURES

- conf/machine/qcom-armv8a.conf
- recipes-bsp/images/initramfs-firmware-db8074-image.bb
- recipes-bsp/images/initramfs-firmware-dragonboard820c-image.bb
- recipes-bsp/images/initramfs-firmware-image.bb
- recipes-bsp/images/initramfs-firmware-mega-image.bb
- recipes-bsp/images/initramfs-firmware-qar2130p-image.bb
- recipes-bsp/images/initramfs-firmware-rb12-image.bb
- recipes-bsp/images/initramfs-firmware-sm8150-hdk-image.bb
- recipes-bsp/images/initramfs-firmware-sm8350-hdk-image.bb
- recipes-bsp/images/initramfs-firmware-sm8450-hdk-image.bb
- recipes-bsp/images/initramfs-firmware-sm8550-hdk-image.bb
- recipes-bsp/images/initramfs-firmware-sm8650-hdk-image.bb
- recipes-bsp/packagegroups/packagegroup-dragonboard-apq8074.bb
- recipes-bsp/packagegroups/packagegroup-dragonboard410c.bb
- recipes-bsp/packagegroups/packagegroup-dragonboard820c.bb
- recipes-bsp/packagegroups/packagegroup-dragonboard845c.bb
- recipes-bsp/packagegroups/packagegroup-qar2130p.bb
- recipes-bsp/packagegroups/packagegroup-rb1.bb
- recipes-bsp/packagegroups/packagegroup-rb2.bb
- recipes-bsp/packagegroups/packagegroup-rb3gen2.bb
- recipes-bsp/packagegroups/packagegroup-rb5.bb
- recipes-bsp/packagegroups/packagegroup-sm8150-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8350-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8450-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8550-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8650-hdk.bb
It makes sense to define several packagegroups for each of the boards:
- firmware
- hexagon-dsp-binaries
- kernel modules
- (maybe other)
Restructure current recipes by splitting the DSP binaries to separate packagegroups. It makes it easier to add per-board packagegroups in future.
> Restructure packagegroups

- conf/machine/qcs6490-rb3gen2-core-kit.conf
This machine config doesn't include qcom-armv8.inc, on purpose, so include the firmwares here manually.
> qcs6490-rb3gen2-core-kit: add `packagegroup-rb3gen2-firmware` to `MACHINE_ESSENTIAL_RECOMMENDS`

- recipes-bsp/packagegroups/packagegroup-dragonboard845c.bb
- recipes-bsp/packagegroups/packagegroup-rb5.bb
Pull in SLPI firmware for the RB3 and RB5 boards.
While the upstream kernel doesn't yet enable those DSP, installing the firmware helps with the experiments.
> Install Sensors DSP firmware for RB3 and RB5 boards

- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00058.0.bb
Fix incorrect CDT for qcs9100-ride-sx, which is based on ride-sx v3 instead.
> firmware-qcom-boot-qcs9100: use correct ride-sx v3 cdt

- recipes-bsp/firmware/firmware-qcom-qar2130p.bb
- recipes-bsp/hexagon-dsp-binaries/hexagon-dsp-binaries_20250211.bb
- recipes-bsp/hexagon-dspso/hexagon-dspso-qcom-qar2130p.bb
- recipes-bsp/hexagon-dspso/hexagon-dspso-qcom-sm8150-hdk.bb
- recipes-bsp/hexagon-dspso/hexagon-dspso-qcom-sm8350-hdk.bb
- recipes-bsp/hexagon-dspso/hexagon-dspso-qcom-sm8450-hdk.bb
- recipes-bsp/hexagon-dspso/hexagon-dspso-qcom-sm8550-hdk.bb
- recipes-bsp/hexagon-dspso/hexagon-dspso-qcom-sm8650-hdk.bb
- recipes-bsp/hexagon-dspso/hexagon-dspso.inc
- recipes-bsp/images/initramfs-firmware-mega-image.bb
- recipes-bsp/packagegroups/packagegroup-qar2130p.bb
- recipes-bsp/packagegroups/packagegroup-sm8150-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8350-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8450-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8550-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8650-hdk.bb
Follow the firmware-qcom-nhlos.inc / firmware-qcom-adreno.inc approach and provide a way to create packages with  DSP libraries for the Qualcomm devkits. The developer must manually specify DSPSO_URI:pn-hexagon-dspso-qcom-foo variable in conf/local.conf.
> Package Hexagon DSP binaries for Qualcomm HDK boards

- conf/machine/qcm6490-idp.conf
- conf/machine/qcs6490-rb3gen2-core-kit.conf
- conf/machine/qcs9100-ride-sx.conf
Add qcom-sa8775p-ride hexagon dsp firmware binary packages to qcs9100-ride-sx images to use DSP and NPU.
> Add Hexagon DSP bin pkgs to qcs6490 & qcs9100 based machines

- conf/machine/include/qcom-common.inc
It should say `usbhost` instead
> qcom-commonc.inc: fix `ushbost` typo

- ci/base.yml
I believe the extra /git/ is an artifact of the past/legacy architecture. I just checked with the YP admins and they confirm that we should use the link without the extra /git/.
> ci: update the link of meta-yocto

- conf/machine/include/qcom-qcs6490.inc
- conf/machine/include/qcom-qcs9100.inc
- conf/machine/include/qcom-sa8155p.inc
- conf/machine/include/qcom-sdm845.inc
- conf/machine/include/qcom-sm8250.inc
- conf/machine/qcom-armv8a.conf
- recipes-bsp/packagegroups/packagegroup-qcom.bb
- recipes-devtools/debugcc/debugcc_git.bb
- recipes-devtools/pil-squasher/pil-squasher_git.bb
- recipes-devtools/qmic/qmic_git.bb
- recipes-support/pd-mapper/pd-mapper_git.bb
- recipes-support/qrtr/qrtr_git.bb
- recipes-support/rmtfs/rmtfs_git.bb
- recipes-support/tqftpserv/tqftpserv_git.bb
- recipes-test/diag/diag_git.bb
- recipes-test/images/initramfs-tiny-image.bb
Define and add qcom-boot-essential & qcom-boot-additional user space package groups to qcs6490 & qcs9100 images to ensure all basic user space pkgs required for booting the device are present
> Add boot essential user space package groups to qcs6490 & qcs9100 images

- ci/staging-kernel-provider.yml
- recipes-kernel/linux/linux-qcom-staging_6.12.bb
This PR is submitted based on the discussions that happened in [PR745](https://github.com/qualcomm-linux/meta-qcom/pull/745) and sync-ups with @ndechesne and @ricardosalveti about the need for a recipe to build a staging kernel tree with additional patches, especially for boards based on QCS9100 & QCS6490. For the early enablement of other Qcom technologies such as Multimedia and Connectivity on these boards, we need this staging kernel to be built.
This staging kernel tree includes additional patches on top of the 6.12 kernel, many of which are in the process of being upstreamed. Starting with 6.12, this tree will continue to catch up with the latest releases (6.13, 6.14, etc.), with patches being dropped and rebased in the process. Eventually, all patches from this staging kernel will …
> Add a recipe to compile qcom staging kernel.

- conf/machine/qcs6490-rb3gen2-core-kit.conf
- recipes-kernel/linux/linux-yocto-dev.bbappend
- recipes-kernel/linux/linux-yocto-dev/drivers/0001-media-qcom-camss-update-clock-names-for-sc7280.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0001-arm64-dts-qcom-sc7280-Add-support-for-camss.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0002-arm64-dts-qcom-qcs6490-rb3gen2-vision-mezzanine-Add-.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0002-media-dt-bindings-update-clocks-for-sc7280-camss.patch
Frame Capture Test
```
media-ctl --reset
media-ctl -v -V '"imx577 '19-001a'":0[fmt:SRGGB10/4056x3040 field:none]'
media-ctl -V '"msm_csiphy3":0[fmt:SRGGB10/4056x3040]'
media-ctl -V '"msm_csid0":0[fmt:SRGGB10/4056x3040]'
media-ctl -V '"msm_vfe0_rdi0":0[fmt:SRGGB10/4056x3040]'
media-ctl -l '"msm_csiphy3":1->"msm_csid0":0[1]'
media-ctl -l '"msm_csid0":1->"msm_vfe0_rdi0":0[1]'
read -p "Start capturing " foo
yavta -B capture-mplane -c -I -n 5 -f SRGGB10P -s 4056x3040 -F /dev/video0
```
Videosink test (gstreamer)
`gst-launch libcamerasrc ! videoconvert ! autovideosink`
**Notes**
Note that the 12MP camera sensor (`imx577`) is multiplanar and therefore[ not supported natively](https://github.com/PipeWire/pipewire/blob/master/spa/plugins/v4l2/v4l2-utils.c#L80) by Pipewire. The libcamera spa …
> sc7280: camera subsystem, rb3gen2-vision-mezzanine

- conf/machine/qcs9100-ride-sx.conf
Set QCOM_DTB_DEFAULT to qcs9100-ride-r3 as it is the most common and more widely available ride sx development target.
Revision 3 of the board uses a different PHY for the two ethernet ports and supports 2.5G speed.
Both development targets we use in our lab are R3.
> qcs9100-ride-sx: set QCOM_DTB_DEFAULT to qcs9100-ride-r3

- ci/base.yml
Enable Predictable Network Interface Names by default in order to have a stable interface naming in our testing infrastructure.
> ci: base: enable pni-names in DISTRO_FEATURES

- conf/machine/include/qcom-qcm2290.inc
Add qcom-boot-essential and qcom-boot-additional package groups for qcs9100 devices to ensure basic user space support for booting is present.
> qcom-qcm2290: Add boot essential userspace package groups to image

- classes-recipe/image_types_qcom.bbclass
- conf/machine/qrb2210-rb1-core-kit.conf
- recipes-bsp/partition/qcom-partition-confs/qcm2290-partitions.conf
As noted in #806 the qcomflash dir for the RB1 board misses several files, which can cause errors during flashing.
- Install boot image into the qcomflash dir and use it for `boot_a`/`boot_b` partitions
- Don't flash `persist` and `logfs`, they are unused by Linux
- Don't flash firmware and DSP partitions, they are unused with meta-qcom
Closes #806
> Fix qcomflash dir for RB1 board

- recipes-bsp/packagegroups/packagegroup-machine-essential.bb
To have more hardware features working on the supported machines out of the box we should add, at the very least, add drivers and firmware to` MACHINE_ESSENTIAL_*.`
This PR adds _fastrpc, msm, qcom-stats, rtc-pm8xxx and venus-enc/dec_ kernel modules to qcom-common.inc. This should be a big improvement over the status quo, but should be evaluated each time a machine is added or removed.
The commit to the RB3 machine adds virtually all kernel modules that were autoloaded, minus coresight.
> RFC: Populate MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS with packagegroups

- conf/machine/include/qcom-qcs6490.inc
- conf/machine/include/qcom-qcs9100.inc
Several SoC configs include PCIe-specific flags, which are not supposed to be used in production environment. Drop those flags.
> Drop PCIe-related kernel command line options

- ci/lava/qrb2210-rb1-core-kit/boot.yaml
Add LAVA test job template for qrb2210-rb1-core-kit. The jobs is the same as for other existing boards.
> ci: add qrb2210-rb1-core-kit boot test job

- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
when androidboot.serialno is not available in cmdline then populate adb serial number from firmware platform-parts-info dt entry.
> adb serial number: fall back option to populate serial number

- recipes-kernel/linux/linux-yocto-dev.bbappend
- recipes-kernel/linux/linux-yocto-dev/drivers/0004-clk-qcom-lpassaudiocc-sc7280-Add-support-for-LPASS-r.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0001-arm64-dts-qcom-sc7280-Add-gpr-node.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0001-dt-bindings-clock-qcom-Add-compatible-for.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0001-dts-rb3gen2-soundwire-checkin.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0002-arm64-dts-qcom-qcm6490-idp-Update-the-LPASS.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0002-arm64-dts-qcom-sc7280-Add-WSA-SoundWire-and-LPASS-su.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0003-arm64-dts-qcom-qcs6490-rb3gen2-Modify-WSA-and-VA-mac.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0003-arm64-dts-qcom-qcs6490-rb3gen2-Update-the-LPASS-audi.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0004-arm64-dts-qcom-qcs6490-rb3gen2-add-WSA8830-speakers-.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0005-arm64-dts-qcom-qcs6490-rb3gen2-Add-sound-card.patch
Enable audio support on RB3Gen2.
Tested:
**- output:**
`aplay` to main board speaker outputs
**- input**
microphone not tested
```
amixer -c 0 cset iface=MIXER,name='SpkrLeft PA Volume' '20'
amixer -c 0 cset iface=MIXER,name='WSA RX0 MUX' 'AIF1_PB'
amixer -c 0 cset iface=MIXER,name='WSA_RX0 INP0' 'RX0'
amixer -c 0 cset iface=MIXER,name='WSA_COMP1 Switch' '1'
amixer -c 0 cset iface=MIXER,name='SpkrLeft WSA MODE' '0'
amixer -c 0 cset iface=MIXER,name='SpkrLeft COMP Switch' '1'
amixer -c 0 cset iface=MIXER,name='SpkrLeft BOOST Switch' '1'
amixer -c 0 cset iface=MIXER,name='SpkrLeft DAC Switch' '1'
amixer -c 0 cset iface=MIXER,name='SpkrLeft VISENSE Switch' '0'
amixer -c 0 cset iface=MIXER,name='WSA_RX0 Digital Volume'  '85'
amixer -c 0 cset iface=MIXER,name='SpkrRight WSA MODE' '0'
amixer -c …
```
> rb3gen2: lpass 

- conf/machine/include/qcom-qcm2290.inc
- conf/machine/include/qcom-qcs6490.inc
Use `packagegroup-machine-essential-qcom-qcs6490-soc` and `packagegroup-machine-essential-qcom-qcm2290-soc` to pull SoC-specific packages into images.
> Use new SoC-specific essential packagegroups

- .github/workflows/build-yocto.yml
We initially used KAS_REPO_REF_DIR to keep a local copy of the repos mirrors,
to avoid fetching projects from scratch in CI. However, it is implemented such
that the mirrors, once created by kas the first time, are never updated by kas,
they are 'read only'.
Sometimes the fetch from upstream fails and the KAS ended up falling back
to the old content of the mirrors, silently. To fix this we will pre-fetch
all ref front the origin the repos in KAS_REPO_REF_DIR.
We will for each repo retry 3 times sleeping 10 seconds between attempts.
Fixes https://github.com/qualcomm-linux/meta-qcom/issues/712
> ci: pre-fetch KAS_REPO_REF_DIR with just git

- ci/base.yml
The Yocto Project infrastructure has been mostly unreachable for the past week, so switch to more reliable mirrors where possible.
Since meta-yocto is, well, a Yocto Project project, this isn't mirrored by OE.
> ci/base.yml: switch to github.com/openembedded mirrors where possible

- classes-recipe/image_types_qcom.bbclass
- conf/machine/include/qcom-base.inc
"Having a handy 'vmlinux' would be helpful for debugging kernel issues. Start generating vmlinux and make it available along with the kernel image."
> Deploy vmlinux for kernel debugging

- recipes-bsp/images/initramfs-firmware-mega-image.bb
In order to check for conflicts, add packagegroups for the SA8775P-RIDE board to the mega-image.
> initramfs-mega-image: add SA8775P-RIDE packagegroups

- conf/machine/qcm6490-idp.conf
- conf/machine/qcs6490-rb3gen2-core-kit.conf
- conf/machine/qcs9100-ride-sx.conf
The linux-qcom-staging kernel can produce an additional set of DTB files called 'addons DTB' files with downstream additions. Build them along with upstream DTB files to allow users to use downstream features.
> Build add-on DTBs with linux-qcom-staging kernel 

- .github/workflows/build-yocto.yml
- ci/yocto-pybootchartgui.sh
Create buildchart.svg with the buildstats collected data. We have the buildstats enabled but the output is hard to read and understand. The openembedded-core pybootchartgui scripts can process this logs and generates some pretty charts.
For each Yocto build, this will generate a github artifact by machine like `buildchart-qcm6490-idp.zip` with an svg image inside https://github.com/qualcomm-linux/meta-qcom/actions/runs/14362539141/artifacts/2916117283
> ci: add yocto-pybootchartgui

- recipes-graphics/mesa/mesa.bbappend
- recipes-graphics/mesa/mesa/0001-freedreno-Add-initial-A702-support.patch
- recipes-graphics/mesa/mesa/0002-freedreno-A702-fixes-for-deqp-vk.patch
- recipes-graphics/mesa/mesa/0003-freedreno-fix-compilation.patch
The QRB2210 / QCM2290 SoC uses A702, which is not currently supported by Mesa. Import patches from the MR ([0]) and add a patch on top that fixes build issues.
[0] https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27665
> mesa: add support for QCM2290

- conf/machine/qcom-armv7a.conf
- conf/machine/qcom-armv8a.conf
- recipes-kernel/linux/linux-yocto_%.bbappend
Rather than clobbering linux-yocto (and linux-yocto-dev) with machine-specific inherits, specify required classes using the KERNEL_CLASSES variable.
> Use KERNEL_CLASSES to pull in image-related classes

- recipes-support/initrdscripts/initramfs-module-copy-modules_1.0.bb
- recipes-support/rust-android-sparse/rust-android-sparse_0.6.0.bb
Consequence of https://github.com/openembedded/bitbake/commit/24772dd2ae6c0cd11540a260f15065f906fb0997.
> Fix bitbake lack of whitespace warnings

- .github/CODEOWNERS
- README.md
As an organizational guideline, it is preferred to use the oss.qualcomm.com email ID instead of the quicinc email ID.
> Email update for vkraleti

- recipes-bsp/packagegroups/packagegroup-qcom.bb
All initramfs-\*-image recipes use NO_RECOMMENDS to keep the size minimal. The commit ebf3168 ("packagegroups: Define QCOM userspace helper packagegroups") made initramfs-tiny-image to pull     packagegroup-qcom-* packages, which RRECOMMENDs platform packages     instead of RDEPENDing on them, thus all testing initramfs images have     lost corresponding Qualcomm tools.
Make packagegroup-qcom use RDEPENDS instead of RRECOMMENDS in order to     brign tool packages back.
> packagegroup-qcom: use RDEPENDS instead of RRECOMMENDS

- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs6490_00075.0.bb
Firmware available as part of the Qualcomm Linux 1.4 release.
Known changes:
- Boot KPI optimizations
- Update memmap holes dynamically as conventional memory
- Minor bug fixes
- Supporting 32-bit OEM ID
> firmware-qcom-boot-qcs6490: update to 00075.0

- recipes-bsp/partition/files/qcs9100-partitions.conf
There is no partition type argument, should be type-guid instead.
> qcom-partition-conf: qcs9100: fix type argument

- .github/workflows/build-yocto.yml
- .github/workflows/pr.yml
- .github/workflows/publish_artifacts.py
The current artifact upload logic requires the self-hosted runner and the file-server to share the same NFS volume as a means of uploading artifacts. This change decouples that so that we could use any runner and still upload artifacts.
We do this by leveraging the GITHUB_TOKEN included in every CI job (including PRs from forked repositories). This is an ephemeral token only valid during the lifetime of the workflow. By granting it read access to the "security-events" API, our file-serve can assert the token it gets is a valid qualcomm-linux token before allowing an upload to happen.
The upload logic gets a little hard to maintain with inline yaml and shell script, so I've created a Python helper to do the upload. It has a few handy features:
* parallel uploads
* upload progress
* better …
> ci: Convert to yet another artifact upload API

- .github/workflows/nightly-build.yml
- .github/workflows/push.yml
We need this permission for merge commits also, so that we can verify the API token is indeed a member of qualcomm-linux that can publish artifacts.
> fixup! ci: Convert to yet another artifact upload API (#861)

- conf/machine/include/qcom-qcm2290.inc
- conf/machine/include/qcom-qcs6490.inc
- conf/machine/include/qcom-qcs8300.inc
- conf/machine/include/qcom-qcs9100.inc
Use of earlycon makes it harder to debug issues (see [RB8 boot logs](https://github.com/qualcomm-linux/meta-qcom/actions/runs/14848561348/job/41689454218) for example). Disable earlycon in order to make it possible to get the full boot log.
> Disable earlycon for all machines

- classes/uki-esp-image.bbclass
Fix the order of tasks in uki-esp-image class so that the Linux UKI file has a chance to land in the generated VFAT image.
> uki-esp-image: fix order of tasks

- recipes-kernel/images/esp-qcom-image.bb
Both were removed as a side effect of https://github.com/qualcomm-linux/meta-qcom/pull/722
> uki: add back support for console and KERNEL_CMDLINE_EXTRA in the kernel cmdline

- .github/workflows/test.yml
It is usually important to get the image tested on all boards rather than stopping on the first failure. Specifi fail-fast:false to the submit-job in order to let all image tests finish if one of them fails.
> CI: disable fail-fast for CI job submission

- recipes-kernel/linux/linux-yocto-dev.bbappend
- recipes-kernel/linux/linux-yocto-dev/workarounds/0001-iommu-Fix-crash-in-report_iommu_fault.patch
Import patch from upstream kernel fixing the kernel crash during reporting IOMMU fault
> linux-yocto-dev: import patch fixing the iommu issue

- recipes-bsp/images/initramfs-firmware-image.bb
- recipes-bsp/images/initramfs-firmware-qcs8300-ride-image.bb
- recipes-bsp/images/initramfs-firmware-sa8775p-ride-image.bb
Add initramfs images with SA8775P and QCS8300 firmware for the Ride SX boards.
> SA8775P and QCS8300 initramfs images

- ci/lava/qcs6490-rb3gen2-core-kit/boot.yaml
- ci/lava/qcs9075-iq-9075-evk/boot.yaml
- ci/lava/qcs9100-ride-sx/boot.yaml
- ci/lava/qrb2210-rb1-core-kit/boot.yaml
Run dmesg as a part of boot testing on the hardware. dmesg command is only executed. No filtering is done for warning or errors.
> ci: add dmesg to boot test

- classes-recipe/image_types_qcom.bbclass
- recipes-bsp/firmware-boot/firmware-qcom-boot-common.inc
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00075.0.bb
SAIL firmware is available as part of the boot firmware r1.0_00075.0 release, and required by QCS9100.
> Deploy QCS9100 SAIL firmware

- .github/workflows/build-yocto.yml
- ci/initramfs-test.yml
Extend kas build logic to also build a series of initramfs images (test and firmware related), to be used with general kernel validation.
> ci: add and build kas configuration file for initramfs images

- .github/workflows/build-yocto.yml
- ci/initramfs-test.yml
initramfs-firmware-image recipe has been dropped with PR #889 ,  remove it from the list of initrd test images as well.
> Drop initramfs-firmware-image from initramfs-test.yml

- conf/machine/qcs9075-iq-9075-evk.conf
Commit d55a42e05d42 ("linux-yocto-dev: refresh qcs9075-iq-9075-evk DT patches") has updated KERNEL_DEVICETREE, but failed to update QCOM_DTB_DEFAULT. Thus dtb.bin isn't being created, which makes tests on the RB8 board fail.
Point QCOM_DTB_DEFAULT to point to the same DTB as KERNEL_DEVICETREE does.
> qcs9075-iq-9075-evk: fix QCOM_DTB_DEFAULT

- .github/workflows/build-yocto.yml
Join the jobs kas-lock and kas-mirror in a new kas-setup job. This will improve the efficiency and both jobs has no dependencies and can be easily done in one.
> ci: build-yocto: join kas-lock and kas-mirror in kas-setup job

- .github/workflows/build-yocto.yml
Build URL is added to the summary and will be displayed in the workflow presentation page in github.
> workflows: add build download URL to summary

- ci/distro.yml
Default qualcomm distro name was updated from qcom-wayland to
qcom-distro, and the default layer dependency now includes meta-oe,
meta-networking and meta-python.
> ci: distro: update distro name and dependencies

- recipes-graphics/wayland/weston-init.bbappend
DRM should be the default weston backend on qcom devices.
> weston-init: set default weston backend to drm

- recipes-bsp/packagegroups/packagegroup-sa8775p-ride.bb
Available as part of linux-firmware 20250509 from oe-core.
> packagegroup-sa8775p-ride-firmware: include sa8775p-qupv3fw

- ci/distro.yml
This enables meta-xfce and friends for DISTRO='qcom-distro'
> ci/distro.yml: enable meta-xfce and its dependencies

- .github/workflows/lava-schema-check.yml
Use LAVA release 2025.04 to check job templates schema. LAVA instance where the test jobs are run were recently upgraded to the same version.
> workflows: update LAVA schema check to 2025.04

- recipes-devtools/qdl/qdl_git.bb
There have been 48 commits to the master branch of QDL since we last updated the recipe. Let's point at the current master revision to bring it up to date.
While at it, also flesh out the recipe description a bit.
>  qdl: update source revision to newest master 

- README.md
Add a minor qualcomm internal note pointing to the internal github and oss training pages.
> README: add note for qcom internal github/oss pages

- recipes-bsp/packagegroups/packagegroup-qcom.bb
Switch to using RDEPENDS for including miscellaneous packages in packagegroup-qcom to ensure they are built by default.
> Use RDEPENDS instead of RRECOMMENDS in packagegroup-qcom

- recipes-bsp/packagegroups/packagegroup-qcom.bb
- recipes-support/libdmabufheap/libdmabufheap_1.0.0.bb
Add recipe to compile libdmabuf which provices apis to access dmabuf heap framework.
> recipes-bsp: libdmabufheap: Add recipe to compile libdmabufheap

- ci/lava/dragonboard-410c/boot.yaml
- ci/lava/dragonboard-820c/boot.yaml
The templates had wrong passwords for downloading rootfs. Boot image name for db820c was copied from 410c and not changed. Download path was missing "qcom-armv8a". These issues caused the jobs to fail. This patch fixes all mentioned problems.
> ci: fix LAVA templates for dragonboard-410c and 820c

- recipes-devtools/qdl/qdl_git.bb
The most recent qdl release is 2.1, which is 6 months old and we are referencing a newer revision from git instead.
Still, that git revision is based off a release, so it makes more sense for PV to start with the revision, so when there is an actual newer release, possible consumers of the package feed see that there is an actual update. There is no loss of information, because the source revision appended after the '+' remains as is.
> qdl: replace 0.0 in recipe PV with latest release

- ci/mirror.yml
The project [1] is switching the way handle our CDN provision of sstate objects, update the URL accordingly.
[1] https://git.yoctoproject.org/yocto-docs/commit/?id=406e8a8e30404c0538f5aa46f211540bae2b206b
> ci/mirror: Switch to new CDN

- recipes-kernel/linux/linux-yocto-dev.bbappend
- recipes-kernel/linux/linux-yocto-dev/workarounds/0001-media-venus-Fix-probe-error-handling.patch
- recipes-kernel/linux/linux-yocto-dev/workarounds/0001-media-venus-hfi-explicitly-release-IRQ-during-teardo.patch
- recipes-kernel/linux/linux-yocto-dev/workarounds/0001-media-venus-protect-against-spurious-interrupts-duri.patch
Backport and add fromlist patches required to fix venus probe crashes on rb3gen2, which happens quite often on boot and locks up the kernel completely on reboots.
> linux-yocto-dev: import patches fixing venus probe crashes

- classes-recipe/image_types_qcom.bbclass
Qualcomm ARMv7 machines don't use EFI, ESP and UKI. Explicitly disable QCOM_ESP_IMAGE for those machines in order to let qcom-distro / qcom-multimedia-image work for qcom-armv7a.
> image-types-qcom: disable ESP for armv7 machines

- .github/workflows/build-yocto.yml
- ci/base.yml
- ci/distro.yml
Fixes for meta-qcom-distro builds, including extended lockfile, updated kas-build.yml, correct include order of the kas yml fragment and set qcom-multimedia-image as default distro image.
First two changes are general kas clean up fixes (removing deprecated options).
> ci: fix meta-qcom-distro builds

- .github/workflows/build-yocto.yml
- ci/qcs615-adp-air.yml
- conf/machine/include/qcom-qcs615.inc
- conf/machine/qcs615-adp-air.conf
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs615.inc
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs615_00095.0.bb
- recipes-bsp/partition/files/qcs615-partitions.conf
- recipes-bsp/partition/qcom-partition-conf-qcs615-adp-air.bb
- recipes-kernel/linux/linux-yocto-dev.bbappend
- recipes-kernel/linux/linux-yocto-dev/qcs615-board-dts/0001-arm64-dts-qcom-qcs615-Add-Command-DB-support.patch
Enable QCS615 support, include:
1. dts patches for kernel
2. partition conf for qcs615
3. firmware recipe to take care deploy boot non-hlos.
4. machine conf
5. github CI enablement for qcs615
> Add support for QCS615-adp-air machine

- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs6490_00075.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs6490_00095.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs8300_00075.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs8300_00095.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00075.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00095.0.bb
A new firmware drop 00095.0 is available. Migrate to it for qcs6490, qcs9100, qcs8300 based machines.
> firmware-qcom-boot: update to 00095.0

- recipes-kernel/linux/linux-qcom-next_git.bb
To avoid fetcher issues caused by the retargeting of the `qcom-next` branch on every tag upmerge, use `nobranch=1` in `SRC_URI`. This allows BitBake to search for the specified `SRCREV` across the entire repository, including commits that are no longer associated with the current branch tip but are still preserved by tag.
The `branch` parameter should be used only in cases like `devupstream`, where a stable and consistent branch reference is expected.
> linux-qcom-next: use 'nobranch=1' in SRC_URI to support retagged commits

- recipes-bsp/packagegroups/packagegroup-qcom.bb
- recipes-graphics/graphicsdlkm/files/kgsl.rules
- recipes-graphics/graphicsdlkm/graphicsdlkm_1.0.bb
graphicsdlkm recipe introduces the QUALCOMM KGSL driver, which is responsible for managing the Adreno GPU.
Key responsibilities of the driver include:
- GPU memory management
- Command submission to GPU
- GPU Power management
- Providing debug and profiling interface to user-space
> Add graphicsdlkm recipe

- recipes-support/audio/alsa-ucm-conf/0001-ucm2-Qualcomm-Update-the-QCM6490-and-QCS6490-hifi-co.patch
- recipes-support/audio/alsa-ucm-conf/0002-ucm2-Qualcomm-Update-the-HIFI-enable-mixer-commands-.patch
- recipes-support/audio/alsa-ucm-conf_%.bbappend
Backported two patches to update UCM2 configurations. QCM6490 and QCS6490 HiFi codec configuration. HIFI enable mixer commands for Qualcomm platforms. Added bbappend file to integrate the patches into alsa-ucm-conf.
> alsa-ucm-conf: Backport UCM2 patches for Qualcomm platforms

- .github/workflows/build-yocto.yml
Each build exports close to 590 files, because it was initially decided to 'blindly' publish the deploy_dir folder which is bitbake output directory.
In a typical build, there are 25 symlinks which end up being duplicate files on the file server (1.3GB per platform). The symlinks are convenient/shortened filenames, and don't need to be published.
deploy_dir also contains 'partitions' folder which is an intermediate artifact used to generate the image GPT files, with 490 files.
To clean up the published files, and to avoid growing it by mistake in the future, this commit switches the logic. Instead of publishing the entire deploy_dir folder (with minimal cleanup), the CI job now only publishes real files (no symlinks) located in the root of deploy_dir. Any additional files needed (later) …
> ci: reduce the amount of files published for each build

- ci/base.yml
CI images are primarily used for testing, and enabling ramdump collection, page owner tracking is helpful for debugging kernel oops issues. Update the kernel command line via `local.conf` to include the necessary options to support these features.
> enable kernel debug features by default in CI

- conf/machine/qcs615-adp-air.conf
- recipes-bsp/packagegroups/packagegroup-qcs615-adp-air.bb
Add firmware packagegroups for the QCS615-ADP-Air board.
> packagegroup-qcs615-adp-air: packagegroups for QCS615-ADP-Air

- ci/qcom-distro.yml
This enables recipes like `docker-moby` and `podman`.
Related to https://github.com/qualcomm-linux/meta-qcom-distro/issues/53
> ci/qcom-distro.yml: enable meta-virtualization and its dependencies

- .github/workflows/build-yocto.yml
In 918119a8a546 (ci: reduce the amount of files published for each build), we reduced the amount of files published by the job. However some of the files removed are actually used by LAVA job template (see ci/lava/*/boot.yaml).
Bitbake typically artifacts with full, unique name that includes a timestamp, such as
core-image-base-qcs6490-rb3gen2-core-kit.rootfs-20250728160211.qcomflash.tar.gz, and it also creates a convenient, shorter symlink, such as core-image-base-qcs6490-rb3gen2-core-kit.rootfs.qcomflash.tar.gz.
LAVA uses the shorter link, because at this stage of the pipeline the timestamp is not known. When we removed the symlink, it broke the LAVA tests. The right thing to do is most likely to export the timestamp from the build job, and use the full name with the timestamp in the …
> ci: include symlink for files used by LAVA tests

- .github/workflows/build-yocto.yml
- conf/machine/include/qcom-common.inc
Fix two issues with CI:
- don't remove built artifacts for qcom-armv8a builds
- copy all symlinks as expected
> ci: fix two issues breaking testing on dragonboard boards

- ci/lava/qcs8300-ride-sx/boot.yaml
This is a clone of the template for qcs9100-ride-sx with the
device-type changed as the LAVA deployment method is the same.
I have tested with a manual job
https://lava.infra.foundries.io/scheduler/job/86608
> Add LAVA template for qcs8300-ride-sx machine

- recipes-graphics/mesa/mesa-git/0001-freedreno-don-t-encode-build-path-into-binaries.patch
- recipes-graphics/mesa/mesa-git/0001-meson-misdetects-64bit-atomics-on-mips-clang.patch
- recipes-graphics/mesa/mesa_25.2.0-rc2.bb
In order to be able to test upcoming features of the 25.2 branch, which includes A702 support, OpenCL improvements and RGB888 support, add recipe for RC version of the Mesa library. It will be dropped as soon as OE-core switches to the 25.2.0 (probably soon after the release)
> mesa: add 25.2.0-rc2 version of the recipe

- recipes-kernel/linux/linux-yocto-dev/drivers/0008-PCI-pwrctrl-Add-power-control-driver-for-tc9563.patch
While refreshing TC9563 patchset I didn't notice that one of Kconfig symbols was also renamed in the upstream kernel. This e.g. causes failures on qcom-armv7a machines with the linux-yocto-dev kernels. Correct the Kconfig symbol in the patch.
Fixes: a489721ca174 ("linux-yocto-dev: refresh")
> linux-yocto-dev: fix Kconfig dependency

- .github/workflows/build-yocto.yml
Upload the build artifacts to the specified S3 bucket. This step is
essential to enable Axiom testing, as it relies on these artifacts
being available. Ensure the upload is completed before initiating tests
> ci: upload build artifacts to S3 bucket

- recipes-test/images/initramfs-test-full-image.bb
Add the igt-gpu-tools-tests package to initramfs-test-full-image.bb to enable support for DRM driver testing.
Fixes [issue#1000](https://github.com/qualcomm-linux/meta-qcom/issues/1000)
> initramfs-test-full-image: add igt-gpu-tools-tests package

- recipes-kernel/linux/linux-qcom-next_git.bb
As we are migrating to 6.17-rc2, which is a release candidate of the next major release, the version is updated to 6.16-rel+6.17-rc2.
Once 6.17 is officially released, the version will be updated to 6.17.
> Move linux-qcom-next to qcom-next-6.17-rc2-20250825 tag

- recipes-bsp/partition/qcom-partition-conf_git.bb
Current QCS615 partition table include keymint.mbn and secs2d.mbn that are not present in build, which cause PCAT flash failure. Upgrade ptool to include the fix.
> qcom-partition-conf: upgrade revision to fix build flash issue on QCS615

- recipes-kernel/linux/linux-qcom-next_git.bb
qcom-next-6.17-rc3-20250826 is the latest RC tag available in qcom-next kernel.
> move linux-qcom-next to qcom-next-6.17-rc3-20250826 tag

- recipes-test/images/initramfs-test-full-image.bb
Add `fastrpc-tests` package in initramfs-test-full-image for fastrpc
testing.
Closes: https://github.com/qualcomm-linux/meta-qcom/issues/1003
> initramfs-test-full-image: add fastrpc-tests package

- recipes-graphics/kgsl-dlkm/kgsl-dlkm_git.bb
- recipes-kernel/iris-video-module/iris-video-dlkm_1.0.bb
The correct variable is COMPATIBLE_MACHINE, not COMPATIBLE_MACHINES.
> Fix COMPATIBLE_MACHINE usage

- recipes-bsp/packagegroups/packagegroup-qcom.bb
- recipes-graphics/msm-gbm-backend/msm-gbm-backend.bb
msm-gbm-backend sets ANY_OF_DISTRO_FEATURES to 'opengl vulkan', but it's not correct: libgbm isn't being built without EGL / OpenGL being enabled. Drop 'vulkan' from the list of possible DISTRO_FEATUREs and limit the condition to 'opengl' only.
> Don't build MSM GBM backend without 'opengl' DISTRO_FEATURE

- .github/workflows/test-pr.yml
When running tests on pull request it's not easy to identify the proper workflow. This patch adds a link to the workflow to the PR comment. This way it will be easy to find the proper workflow should the tests fail.
> workflows: add comment with action link in PR

- recipes-graphics/adreno/qcom-adreno_1.838.1.bb
CI for qcom-armv7a machine started to fail with the following error:
```
2025-09-18T18:55:56.5099934Z 2025-09-18 18:55:56 - INFO     - NOTE: Resolving any missing task queue dependencies
2025-09-18T18:55:56.9907928Z 2025-09-18 18:55:56 - INFO     - NOTE: Multiple providers are available for runtime libnss-mdns (avahi-libnss-mdns, mdns)
2025-09-18T18:55:56.9908679Z 2025-09-18 18:55:56 - INFO     - Consider defining a PREFERRED_RPROVIDER entry to match libnss-mdns
2025-09-18T18:55:57.4838148Z 2025-09-18 18:55:57 - ERROR    - ERROR: Nothing RPROVIDES 'kgsl-dlkm' (but /work/build/../../repo/recipes-graphics/adreno/qcom-adreno_1.838.1.bb RDEPENDS on or otherwise requires it)
2025-09-18T18:55:57.4839514Z 2025-09-18 18:55:57 - ERROR    - kgsl-dlkm was skipped: incompatible with machine …
```
> Fix qcom-adreno errors on ARMv7-A machines

- recipes-bsp/packagegroups/packagegroup-dragonboard820c.bb
- recipes-bsp/packagegroups/packagegroup-dragonboard845c.bb
- recipes-bsp/packagegroups/packagegroup-qar2130p.bb
- recipes-bsp/packagegroups/packagegroup-qcs615-adp-air.bb
- recipes-bsp/packagegroups/packagegroup-qcs8300-ride.bb
- recipes-bsp/packagegroups/packagegroup-rb1.bb
- recipes-bsp/packagegroups/packagegroup-rb2.bb
- recipes-bsp/packagegroups/packagegroup-rb3gen2.bb
- recipes-bsp/packagegroups/packagegroup-rb5.bb
- recipes-bsp/packagegroups/packagegroup-sa8775p-ride.bb
- recipes-bsp/packagegroups/packagegroup-sm8150-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8350-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8450-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8550-hdk.bb
- recipes-bsp/packagegroups/packagegroup-sm8650-hdk.bb
Enabling of GPU isn't limited to OpenGL-only cases. Install GPU firmware if the distro enabled 'vulkan' or 'opencl' (where applicable).
> Enable GPU firmware even w/o OpenGL

- recipes-bsp/packagegroups/packagegroup-qcom.bb
The qcom-adreno package now pulls in the msm-gbm-backend. Drop it from the packagegroup-qcom's RDEPENDS.
> packagegroup-qcom: drop msm-gbm-backend from RDEPENDS

- conf/machine/iq-8275-evk.conf
- conf/machine/qcs9075-iq-9075-evk.conf
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs615_00096.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs615_00103.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs6490_00095.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs6490_00103.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs8300.inc
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs8300_00095.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs8300_00103.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100.inc
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00095.0.bb
- recipes-bsp/firmware-boot/firmware-qcom-boot-qcs9100_00103.0.bb
- recipes-bsp/partition/qcom-partition-conf_git.bb
- recipes-devtools/partition-utils/qcom-ptool_git.bb
00103.0 release of boot bins has support for FIT based multi-DTB in UEFI. Start consuming this release to be able to enable this feature.
> Update boot bins to 00103.0 release
