- recipes-kernel/linux/files/0001-give-up-on-gcc-ilog2-constant-optimizations.patch
- recipes-kernel/linux/linux-linaro-qcom.inc
Backport a patch from upstream
> linux-linaro-qcom: Fix build with gcc7

- recipes-test/diag/diag/0001-Fix-build-with-musl.patch
- recipes-test/diag/diag_git.bb
> diag: Fix build with musl

- recipes-kernel/linux/linux-linaro-qcomlt_4.14.bb
> recipes-kernel/linux: Update to 4.14.96 LTS

- conf/machine/dragonboard-845c.conf
- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v2.bb
- recipes-kernel/linux/linux-linaro-qcomlt_5.1.bb
> dragonboard-845c: Add firmware recipe and kernel bump

- recipes-graphics/images/qcom-x11-image.bb
distro_features_check is now deprecated
> recipes: Use features_check instead of distro_features_check

- conf/machine/evb4k-qcs404.conf
- conf/machine/include/qcom-qcs404.inc
- recipes-kernel/linux/linux-linaro-qcomlt_5.2.bb
I have created a new pull request, this is based on master branch. Kindly consider this instead of the earlier one which was based on warrior branch.
> Add support for QCS404 based evb4k to master

- recipes-kernel/linux/linux-linaro-qcomlt_5.4.bb
> recipes-kernel/linux: Linux 5.4 bump to fix audio in DB845c

- recipes-test/diag/diag_git.bb
cc5dc0dec3f5 peripherals: Create and use flow context
040982dbdad0 dm: Allow broadcasters to pass a flow context
a3395140dddb watch: Allow flow context to be associated with readq
d2c595e9889e mbuf/watch: Introduce flow control context
3eaf16dd4fee qrtr: Remove writeq when remote goes away
bf8035f68b07 watch: Fix buffer overflow
286187531128 README: Configuration string should be diag_dun
29db5d80b014 common_cmds: Fix warning about address of packed member
73ca38f0175b build: Honor CFLAGS
f46fe32948f4 diag: Add support for version number command
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
> diag: Update to latest version

- conf/layer.conf
> layer.conf: Mark it dunfell (3.1) compatible

- dynamic-layers/openembedded-layer/recipes-navigation/gpsd/gpsd/0001-Introduce-Qualcomm-PDS-service-support.patch
Due to changes on argument order of gpsd_log and use GPSD_LOG
too see rev 81257aeeaf.
> gpsd: Rework PDS service patch changes in gpsd_log

- recipes-graphics/mesa/mesa/0001-freedreno-clear-last_fence-after-resource-tracking.patch
- recipes-graphics/mesa/mesa_%.bbappend
- recipes-support/pd-mapper/pd-mapper_git.bb
- recipes-test/images/initramfs-test-image.bb
> pd-mapper upgrade, Initramfs-test-image add e2fsprogs and mesa patch

- recipes-support/pd-mapper/pd-mapper/0001-pd-mapper-Include-limits.h-for-PATH_MAX.patch
- recipes-support/pd-mapper/pd-mapper_git.bb
> pd-mapper: Fix build with musl

- recipes-kernel/linux/linux-linaro-qcomlt_5.7.bb
Changes,
a7ce3355155d Merge tag 'v5.7.3' into release/qcomlt-5.7
...
9aff2dcc27eb wcn36xx: Fix multiple AMPDU sessions support
44e6ad37e04a wcn36xx: Add ieee80211 rx status rate information
(cherry picked from commit eed9df082f08fe220309d3905bce048969172753)
> recipes-kernel: Linux 5.7 bump to 5.7.5

- conf/machine/include/qcom-common.inc
- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
- dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs_%.bbappend
Implement running adbd on a target device.
> support adbd running on a device

- conf/layer.conf
- conf/machine/include/qcom-common.inc
- dynamic-layers/backports-layer/recipes-devtools/android-tools/android-tools-conf-configfs/qcom/android-gadget-setup.machine
- dynamic-layers/backports-layer/recipes-devtools/android-tools/android-tools-conf-configfs_%.bbappend
Dependencies:
https://review.linaro.org/c/openembedded/meta-backports/+/37709/1
https://review.linaro.org/c/openembedded/meta-backports/+/37708/1
https://review.linaro.org/c/openembedded/meta-backports/+/37707/1
> Adbd dunfell support

- recipes-kernel/linux/linux-linaro-qcomlt_5.11.bb
> linux-linaro-qcomlt: bump 5.11 SRCREV to include few fixes

- recipes-kernel/linux/linux-linaro-qcomlt_5.11.bb
(cherry picked from commit 265412eb676e83c41725001be6feec5b839cb86e)
> linux-linaro-qcomlt: bump 5.11 SRCREV to include few fixes (dunfell)

- conf/machine/include/qcom-sdx55.inc
- conf/machine/sdx55-mtp.conf
- conf/machine/sdx55-telit-fn980.conf
- recipes-kernel/linux/linux-linaro-qcom.inc
Add machine support for SDX55 MTP and Telit FN980
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
> Initial machine support for SDX55

- dynamic-layers/openembedded-layer/recipes-test/images/initramfs-test-image.bbappend
> initramfs-test-image: include cryptsetup

- recipes-test/images/initramfs-test-image.bb
- recipes-test/images/initramfs-tiny-image.bb
> initramfs-test-image: add libdrm-tests

- conf/layer.conf
> layer.conf: add hardknott to compatible release branches

- recipes-bsp/firmware/firmware-qcom-rb5_20210118133815-v2.bb
- recipes-support/fastrpc/fastrpc/0001-apps_std_fopen_with_env-account-for-domain-kinds-whe.patch
- recipes-support/fastrpc/fastrpc/adsprpcd.service
- recipes-support/fastrpc/fastrpc/cdsprpcd.service
- recipes-support/fastrpc/fastrpc/mount-dsp.sh
- recipes-support/fastrpc/fastrpc/usr-lib-rfsa.service
- recipes-support/fastrpc/fastrpc_git.bb
- mount DSP partition to /usr/lib/rfsa
- provide systemd units for *dsprpcd
- fix libraries packaging
> Improve fastrpc-OE integration

- recipes-bsp/firmware/firmware-qcom-rb5_20210331-v4.bb
- recipes-kernel/linux/linux-linaro-qcomlt_5.12.bb
> rb5: update firmware-qcom-rb5 and add linux-linaro-qcomlt_5.12

- recipes-bsp/lt9611uxc-upgrade/lt9611uxc-upgrade/lt9611uxc.service
> lt9611uxc-upgrade: fix systemd condition name

- recipes-kernel/linux/linux-linaro-qcomlt_5.13.bb
> recipes-kernel: Add Linux 5.13 recipe

- recipes-kernel/linux/linux-linaro-qcomlt_5.13.bb
Changes are from stable v5.13.4..v5.13.5.
> recipes-kernel: Linux 5.13 bump to rev a14713f34448 (v5.13.5)

- conf/machine/dragonboard-410c-32.conf
- conf/machine/dragonboard-410c.conf
- conf/machine/evb4k-qcs404.conf
- conf/machine/include/qcom-apq8064.inc
- conf/machine/include/qcom-sdx55.inc
> machines: Adjust for new tune file locations in core

- dynamic-layers/openembedded-layer/recipes-navigation/gpsd/gpsd/0001-Introduce-Qualcomm-PDS-service-support.patch
Refresh the patch adding support for Qualcomm's pds:// NMEA source.
> gpsd: refresh pds patch

- recipes-bsp/firmware/firmware-qcom-dragonboard410c.inc
- recipes-bsp/firmware/firmware-qcom-dragonboard820c_01700.1.bb
- recipes-bsp/firmware/firmware-qcom-dragonboard845c_20190529180356-v4.bb
- recipes-bsp/firmware/firmware-qcom-rb5_20210331-v4.bb
- recipes-bsp/firmware/firmware-qcom-sd-600eval_1.0.bb
- recipes-bsp/firmware/firmware-qcom.inc
I have this patches in my queue for quite some time:
- Extract common settings to separate .inc file
- Drop do_compile function
> Small improvements for the firmware recipes

- dynamic-layers/openembedded-layer/recipes-navigation/gpsd/gpsd/0001-Introduce-Qualcomm-PDS-service-support.patch
> dynamic-layers/recipes-navigation: GPSd update patch to release 3.23.1

- recipes-devtools/skales/skales_git.bb
> skales: Specify branch parameter explicitly in SRC_URI

- recipes-graphics/mesa/files/0002-meson.build-make-TLS-ELF-optional.patch
> recipes-graphics: mesa_git update elf-tls patch

- recipes-kernel/linux/linux-linaro-qcomlt_5.15.bb
No custom changes, window is v5.15.6..v5.15.7.
> recipes-kernel: Linux 5.15 bump to rev 9bc25b368335 (v5.15.7)

- recipes-kernel/linux/linux-linaro-qcomlt/0001-Revert-kbuild-Enable-DT-schema-checks-for-.dtb-targe.patch
- recipes-kernel/linux/linux-linaro-qcomlt_5.16.bb
> linux: Add new .bb files for release/sa8155p-adp/qcomlt-5.16

- recipes-test/images/initramfs-test-image.bb
Add several tools used on a day-to-day basis during development (fastrpc, ALSA and kmscube)
> Add more development tools

- recipes-kernel/images/initramfs-qcom-image.bb
- recipes-kernel/images/initramfs-rootfs-image.bb
- recipes-kernel/linux/linux-qcom-bootimg.inc
- recipes-kernel/packagegroups/packagegroup-qcom-boot.bb
> Rootfs initramfs support

- .github/workflows/premerge.yml
Add initramfs-rootfs-image and initramfs-firmware-image to test that occasional changes do not break them too.
> premerge.yml: also test rootfs and firmware initramfs

- .github/workflows/build-template.yml
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
> CI: tuxsuite: Remove wrong entry in artifacts field

- recipes-test/mybw/mybw_git.bb
mybw is a small utility to check memory performance.
Signed-off-by: Neil Armstrong <neil.armstrong@linaro.org>
> recipes-test: Add mybw recipe

- recipes-test/mybw/mybw/0001-makefile-Allow-CFLAGS-LDFLAGS-from-environment.patch
- recipes-test/mybw/mybw_git.bb
This helps in compiling this will e.g. clang/libc++
> mybw: Pass cflags/ldflags from bitbake

- conf/machine/qcom-armv7a.conf
- conf/machine/qcom-armv8a.conf
- recipes-kernel/linux/linux-linaro-qcomlt_6.0.bb
Backport 6.0 kernel + overrides support from master
> Backport several patches from master

- recipes-devtools/pil-squasher/pil-squasher_git.bb
Update pil-squasher to get pil-splitter binary.
> pil-squasher: update to latest commit

- conf/machine/qcom-armv8a.conf
- recipes-bsp/firmware/firmware-qcom-rb1_20230724-v1.bb
- recipes-bsp/firmware/firmware-qcom-rb2_20230724-v1.bb
- recipes-bsp/firmware/firmware-qcom.inc
- recipes-bsp/packagegroups/packagegroup-firmware-rb1.bb
- recipes-bsp/packagegroups/packagegroup-firmware-rb2.bb
- recipes-kernel/linux/linux-linaro-qcomlt_6.4.bb
- recipes-support/fastrpc/fastrpc/mount-dsp.sh
- recipes-test/images/initramfs-firmware-image.bb
- recipes-test/images/initramfs-firmware-rb12-image.bb
Provide necessary changes to support Qualcomm RB1 and RB2 platforms.
> Support Qualcomm RB1 and RB2 platform

- conf/machine/qcom-armv8a.conf
Add packagegroup-firmware-{rb1,rb2} to MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS.
> qcom-armv8a.conf: also install RB1 and RB2 firmware

- recipes-bsp/firmware/firmware-qcom-sm8150-hdk.bb
- recipes-bsp/packagegroups/packagegroup-firmware-sm8150-hdk.bb
Package firmware for SM8150 HDK (aka HDK855).
> Firmware for SM8150-HDK

- conf/layer.conf
Change-Id: I2e0beb508efb016f08a9b6a1781b39055ecaca1d
> layer.conf: update layer to scarthgap series

- .github/workflows/daily.yml
- .github/workflows/push.yml
Build the current LTS release, scarthgap, on a daily basis.
> CI: include scarthgap into daily builds

- recipes-bsp/firmware-woa/firmware-qcom-lenovo-miix-630_200.0.6.0.bb
- recipes-bsp/firmware-woa/firmware-qcom-lenovo-yoga-c630_200.0.19.0.bb
- recipes-bsp/firmware-woa/firmware-qcom-sc8180x_200.0.105.0.bb
- recipes-bsp/firmware-woa/firmware-qcom-sc8180x_200.0.108.0.bb
- recipes-bsp/firmware-woa/firmware-woa.inc
- recipes-bsp/firmware/firmware-qcom.inc
- recipes-bsp/images/initramfs-firmware-sc8180x-image.bb
Update firmware for sc8180x / Primus to the latest drop.
> Update SC8180X (Asus Primus) firmware

- recipes-kernel/images/linux-qcom-uki.bb
Construct kernel cmdline by reading QCOM_BOOTIMG_ROOTFS, SERIAL_CONSOLES and KERNEL_CMDLINE_EXTRA variables and update the same into uki cmdline.
> Enhance cmdline handling in linux-qcom-uki.bb

- recipes-bsp/firmware-woa/firmware-qcom-x1e80100_200.0.32.0.bb
- recipes-bsp/packagegroups/packagegroup-firmware-x1e80100-crd.bb
After spending more time with the CRD improve packaging.
> Fix x1e80100 CRD firmware packages

- .github/workflows/daily.yml
- .github/workflows/premerge.yml
Add esp-qcom-image to CI to test that changes do not break it.
> Add esp-qcom-image to CI

- .github/workflows/build-template.yml
- .github/workflows/daily.yml
- .github/workflows/premerge.yml
- .github/workflows/push.yml
Backport CI changes to enable matrix-like build approach to the scarthgap branch.
> Backport CI changes to the scarthgap branch

- recipes-bsp/firmware-nexus/firmware-qcom-pixel4.bb
- recipes-bsp/firmware-nexus/firmware-qcom-pixel4a-5g.bb
- recipes-bsp/firmware-nexus/firmware-qcom-pixel4a.bb
- recipes-bsp/firmware-nexus/firmware-qcom-pixel5.bb
- recipes-bsp/firmware-nexus/firmware-qcom-pixel5a-5g.bb
Bump package version to the latest available binary package.
> firmware-qcom-pixel*: bump versions

- classes/linux-qcom-bootimg.bbclass
Make it possible to not set the root= argument in the image's kernel cmdline.
Setting QCOM_BOOTIMG_ROOTFS to "" will skip setting the root= argument.
Determining the rootfs is now deferred to the bootloader. One use-case for this is to support boot slots.
> linux-qcom-bootimg: Make root= cmdline arg optional

- .github/workflows/premerge.yml
- .github/workflows/push.yml
Provide missing input for the CI.
> CI: provide variants for the CI setup

- .github/workflows/build-yocto.yml
- .github/workflows/repolinter.yml
- SECURITY.md
- ci/base.yml
These changes are required for the move from meta-qcom-hwe to meta-qcom
> Updates for move from meta-qcom-hwe to meta-qcom

- README.md
Workflow was renamed as part of
https://github.com/qualcomm-linux/meta-qcom-hwe/pull/125.
> README.md: update build on push / yocto workflow link

- README.md
Change links to point to the new location of the repo.
> README.md: point to the new location

- recipes-bsp/hexagon-dsp-binaries/files/0001-Makefile-provide-clean-target.patch
- recipes-bsp/hexagon-dsp-binaries/hexagon-dsp-binaries_20250109.bb
I forgot to bump SRCREV while updating the recipe, bump it now.
> Two fixes for hexagon-dsp-binaries

- recipes-bsp/hexagon-dsp-binaries/hexagon-dsp-binaries_20250211.bb
Update to the latest hexagon-dsp-binaries release. Package freshly added SA8775P-RIDE firmware.
> hexagon-dsp-binaries: update 20250109 -> 20250211

- recipes-bsp/firmware/firmware-qcom-sar2130p.bb
- recipes-bsp/images/initramfs-firmware-mega-image.bb
- recipes-bsp/images/initramfs-firmware-qar2130p-image.bb
- recipes-bsp/packagegroups/packagegroup-firmware-qar2130p.bb
Package firmware for the Qualcomm QAR2130P development platform.
> recipes-bsp/firmware: package QAR2130P firmware

- ci/lava/qcs9100-ride-sx/boot.yaml
Add basic boot test for qcs9100-ride-sx.
> ci: add test job for qcs9100-ride-sx

- conf/machine/qcs9100-ride-sx.conf
- recipes-bsp/packagegroups/packagegroup-sa8775p-ride.bb
Add firmware packagegroups for the SA8775P-RIDE board.
> packagegroup-sa8775p-ride: packagegroups for SA8775P-RIDE

- recipes-devtools/debugcc/debugcc_git.bb
Updated to the latest revision and changed build system to meson
> debugcc: update to the latest revision

- .github/workflows/build-yocto.yml
- ci/qcm2290.yml
- ci/qrb2210-rb1-core-kit.yml
- conf/machine/include/qcom-qcm2290.inc
- conf/machine/qrb2210-rb1-core-kit.conf
- recipes-bsp/firmware-boot/firmware-qcom-boot-common.inc
- recipes-bsp/firmware-boot/firmware-qcom-boot-qrb2210-rb1_23.12.bb
- recipes-bsp/partition/qcom-partition-confs/qcm2290-partitions.conf
- recipes-bsp/partition/qcom-partition-confs_1.0.bb
- recipes-devtools/partition-utils/qcom-gen-partition-bins_1.0.bb
- recipes-graphics/mesa/mesa.bbappend
- recipes-graphics/mesa/mesa/0001-freedreno-check-if-GPU-supported-in-fd_pipe_new2.patch
This is WIP, just to share what I have so far. It is not boot tested yet.
> RB1 support

- recipes-kernel/linux/linux-qcom-staging_6.12.bb
Update linux-qcom-staging recipe to fetch the latest git revision to pull in several fixes.
> Bump SRCREV of linux-qcom-staging to latest.

- .github/workflows/stales.yml
Workflow to close stale issues and pull requests with no recent activity.
> workflows: add stale workflow for prs and issues

- .github/workflows/build-yocto.yml
- ci/kas-shell-helper.sh
- ci/yocto-check-layer.sh
- ci/yocto-patchreview.sh
- ci/yocto-pybootchartgui.sh
Add kas-shell-helper script and switch to it to execute the kas shell scripts on build-yocto ci
> ci: build-yocto: switch to kas-shell-helper

- classes-recipe/image_types_qcom.bbclass
- recipes-bsp/partition/qcom-partition-conf_git.bb
- recipes-devtools/partition-utils/qcom-ptool_git.bb
qcom-ptool repo is now supporting CDT flashing. Start using this version.
> qcom-ptool: upgrade to revision that supports CDT flashing
